### ISSUE TITLE
Image_url with nfs mount

### ISSUE THREAD

**Issue by sr-as2** [j-a-n/lovelace-wallpanel#10]
Hi,
i'm trying to use a NFS share with image_url but i can't get it working.
I mount /media/photo. In Home Assitant, in the media menu, i can see "local media" -> "photo", with all my photo directories.

I try many wallpanel configuration but it can't display any photo

`image_url: /local/photo/`

**Comment by j-a-n** [comment]
Hi,

what does your configuration.yaml `media_dirs` looks like?

**Comment by sr-as2** [comment]
I haven't got media_dirs in configuration.yaml
i'm using:
`For Home Assistant OS, Supervised and Container users, this folder is by default configured in the path /media`

**Comment by j-a-n** [comment]
Please navigate to the desired folder using the HA Media Browser.
Which URL is displayed in the browser?

**Comment by sr-as2** [comment]
it shows:

`https://myhomeassistant.my/media-browser/browser/app%2Cmedia-source%3A%2F%2Fmedia_source/%2Cmedia-source%3A%2F%2Fmedia_source%2Flocal%2Fphoto`

Strange...

**Comment by j-a-n** [comment]
In this case this should work:

```yaml
wallpanel:
  image_url: /local/photo
```
If not, please see if any error messages are displayed in the browser console.

**Comment by sr-as2** [comment]
Yes it works!
`/local/photo/`

My problem is because i'm reading pictures from a Synology, and Synology DS Photo creates folder @eadir with metadata...so it shows black screen... Can we exclude some folder/files ?

**Comment by j-a-n** [comment]
With version 2.3 of the addon you can use:
```yaml
image_excludes:
  - '/@eaDir'
```
