### ISSUE TITLE
Exif image info no longer works under 2023.4 with wallpanel 4.9.1

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#101]
Since last core update ( I a, on 2023.4.2)
The exif info box no longer shows up.

``` 
wallpanel:  enabled: true  idle_time: 30  enabled_on_tabs:    - default_view  image_url: /  image_fit: scale-down  display_time: 20  hide_toolbar: false  hide_sidebar: false  fullscreen: true  image_order: random  show_exif_info: true  fetch_address_data: true  exif_info_template: >-    <span style="font-family: 'Roboto Condensed', sans-serif; font-size: 1em;    font-weight: 400; color:#FFB90F%22%3E%20%3C/span%3E%20%20%20%20%20%20%20${address.tourism!prefix=!suffix=;%20}%20%20%20%20${adress.country_code|address.country!prefix=!suffix=;%20%20}%20%20%20%20%20${address.town|address.city|address.municipality|adress.village|address.county|address.region!suffix=%20%20%20%20/%20}%20%20${DateTimeOriginal}%20%20%20image_list_update_interval:%207200%20%20screensaver_entity:%20input_boolean.wallpaper_screensaver%20%20info_animation_duration_x:%2050%20%20info_animation_duration_y:%2050%20%20info_animation_timing_function_x:%20steps(1,%20end)%20%20info_animation_timing_function_y:%20steps(1,%20end)%20%20style:%20%20%20%20wallpanel-screensaver-image-info:%20%20%20%20%20%20position:%20absolute%20%20%20%20%20%20bottom:%200.5em%20%20%20%20%20%20right:%201.0em%20%20%20%20%20%20font-size:%202.0em%20%20%20%20%20%20'-webkit-text-stroke':%20'0.02em%20#000'%20%20%20%20%20%20color:%20'#ff9a00'%20%20%20%20%20%20font-weight:%20'900'%20%20%20%20%20%20font-family:%20monospace%20%20%20%20wallpanel-screensaver-info-box:%20%20%20%20%20%20'--wp-card-width':%20800px%20%20%20%20wallpanel-screensaver-info-box-content:%20%20%20%20%20%20'--ha-card-background':%20rgba(131,139,131,0)%20%20%20%20%20%20'--ha-card-box-shadow':%20none%20%20%20%20%20%20text-shadow:%20%3E-%20%20%20%20%20%20%20%20-0.5px%20-0.5px%200%20rgb(17,%2017,%2017),%200.5px%20-0.5px%200%20rgb(17,%2017,%2017),%20-0.5px%20%20%20%20%20%20%20%200.5px%200%20rgb(17,%2017,%2017),%200.5px%200.5px%200%20rgb(17,%2017,%2017)%20%20%20%20%20%20'--primary-text-color':%20'#ffffff'%20%20%20%20%20%20'--secondary-text-color':%20'#dddddd' 
```

**Comment by j-a-n** [comment]
Please edit your post so that the configuration is readable.
Please use a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
Which version of wallpaner are you using?

**Comment by kwithus** [comment]
It’s wallpanel 4.10
I tried to use a code block, no idea why it doesn’t work

**Comment by j-a-n** [comment]
Still unreadable, sorry.

**Comment by kwithus** [comment]
`

exif_info_template: >-
    <span style="font-family: 'Roboto Condensed', sans-serif; font-size: 1em;
    font-weight: 400; color:#FFB90F"> </span>   
    ${address.tourism!prefix=!suffix=; }
    ${adress.country_code|address.country!prefix=!suffix=;  } 
    ${address.town|address.city|address.municipality|adress.village|address.county|address.region!suffix=
    / }  ${DateTimeOriginal} 
  image_list_update_interval: 7200
  screensaver_entity: input_boolean.wallpaper_screensaver
  info_animation_duration_x: 50
  info_animation_duration_y: 50
  info_animation_timing_function_x: steps(1, end)
  info_animation_timing_function_y: steps(1, end)
  style:
    wallpanel-screensaver-image-info:
      position: absolute
      bottom: 0.5em
      right: 1.0em
      font-size: 2.0em
      '-webkit-text-stroke': '0.02em #000'
      color: '#ff9a00'
      font-weight: '900'
      font-family: monospace
    wallpanel-screensaver-info-box:
      '--wp-card-width': 800px
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': rgba(131,139,131,0)
      '--ha-card-box-shadow': none
      text-shadow: >-
        -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px
        0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'

`

ok, I tried it again and now it is readable, no idea what did the difference 
Thanks for looking into it

**Comment by j-a-n** [comment]
Okay, there are some HTML formatting issues.
Please replace
```
  exif_info_template: >-
    <span style="font-family: 'Roboto Condensed', sans-serif; font-size: 1em;
    font-weight: 400; color:#FFB90F"> </span>   
    ${address.tourism!prefix=!suffix=; }
    ${adress.country_code|address.country!prefix=!suffix=;  } 
    ${address.town|address.city|address.municipality|adress.village|address.county|address.region!suffix=
    / }  ${DateTimeOriginal} 
```
with
```
  image_info_template: >-
    <span style="font-family: 'Roboto Condensed', sans-serif; font-size: 1em;
    font-weight: 400; color:"#FFB90F">   
    ${address.tourism!prefix=!suffix=; }
    ${adress.country_code|address.country!prefix=!suffix=;  } 
    ${address.town|address.city|address.municipality|adress.village|address.county|address.region!suffix=
    / }  ${DateTimeOriginal} </span>
```

**Comment by kwithus** [comment]
Thanks, I did change that, however same problem

**Comment by j-a-n** [comment]
Seems like `show_image_info = true` is also missing?

**Comment by kwithus** [comment]
`

show_exif_info: true
  fetch_address_data: true
  image_info_template: >-
    <span style="font-family: 'Roboto Condensed', sans-serif; font-size: 1em;
    font-weight: 400; color:"#FFB90F">    ${address.tourism!prefix=!suffix=; }
    ${adress.country_code|address.country!prefix=!suffix=;  } 
    ${address.town|address.city|address.municipality|adress.village|address.county|address.region!suffix=
    / }  ${DateTimeOriginal} </span> 

`

and I didn’t change anything before it stopped working

**Comment by j-a-n** [comment]
Please remove your complete `style` configuration and try if that fixes the issue.

**Comment by kwithus** [comment]
didn’t make any difference

**Comment by j-a-n** [comment]
Any errors in the browser console?

**Comment by kwithus** [comment]
so far, I couldn’t see anything 
I will try to roll back to 2023.3.x and see whether it works then.
however , I can do that next week only

**Comment by kwithus** [comment]
Today I rolled backte HA Core 2023.3.6, now I can see the exif Infos again. Didn’t make any other changes.
So it must have to do something with HA 2023.4.x
However strange that no one else so far reported this.

**Comment by kwithus** [comment]
Sorry, but it is not yet solved.
As mentioned I noticed the problem first when I updated to 2023.4.x and it was only ‚solved‘ when I rolled back to 2023.3.6
However, what I didn’t realized: Updating to 2023.4.x was accompanied (in my installation) but updating wallpanel from 4.8.something to 4.10.2
I now updated to 2023.4.6 first without updating the wallpanel, everything fine.
As soon as I update wallpanel  to 4.10.2. the problem is back, no exit info shown.
Is there a way to do the update of wallpanel version by version to isolate the issue a little bit more?

**Comment by j-a-n** [comment]
You can select one of the five latest versions in HACS.

**Comment by kwithus** [comment]
Ok, 4.9.0 does work as expected, 4.9.1 not

**Comment by j-a-n** [comment]
Okay. Version 4.9.1 does not support the legacy configuration attributes anymore. Please have a look at the README and use the new attributes, like `show_image_info` instead of `show_exif_info`.
