### ISSUE TITLE
Feature Request - Set options via local storeage

### ISSUE THREAD

**Issue by diginfo** [j-a-n/lovelace-wallpanel#102]
Firstly, great integration, thank you.

It would be nice if as well as being able to set configs via the url, you could also set them in local storeage.

**Comment by diginfo** [comment]
specifically, it would be good if at least the ```wp_enabled``` was configurable via local storeage

**Comment by j-a-n** [comment]
Please explain a little better what you are going to use this for.

**Comment by diginfo** [comment]
Thanks;

As you know, home assistant uses local storage to save the user's UI / desktop configs.

It would be useful to be able to use the same method to configure wallpanel, especially when developing dashboards which include navigation actions, as these actions don't include ?arguments, and each time I view a page that has been navigated to, I have to manually add ?wp_enabled=false and reload the page so that I can continue editing again.

**Comment by j-a-n** [comment]
But how to edit the local storage?
You could also use [Profiles](https://github.com/j-a-n/lovelace-wallpanel#profiles) to enable or disable wallpanel.

**Comment by diginfo** [comment]
In Chrome, clkick the 3 dots on the right > More Tools > Developer Tools, Then in the panel that opens up, select the Application tab, then in the left panel select Local Storage and select your url.

You can add, edit and delete them there or using javascript:
```
var wls = window.localStorage;
if(wls.getItem('mykey') === null){
      wls.setItem('my_key','my_value');
} 

<img width="1728" alt="Screenshot 2023-04-23 at 5 38 59 PM" src="https://user-images.githubusercontent.com/6010010/233832042-9de997a8-d89b-4a32-9309-2dbc4270a9f9.png">



```

**Comment by j-a-n** [comment]
Do you find this more comfortable than switching a profile?

**Comment by kwithus** [comment]
I really like the idea of different profiles, especially as they can be selected through automations that change the input-select.
I currently do use this to switch to a screensaver that only shows my Doorbird camera as soon as someone rings on the door. 
however as more as I use the Wallpanel, as longer the config gets and as mir complicate it gets to edit. 
so yes, I would love to see a more ‚user friendly’ way to edit/config
