### ISSUE TITLE
[Bug] image_url not working as expected

### ISSUE THREAD

**Issue by tadly** [j-a-n/lovelace-wallpanel#103]
I prefer having no wallpaper at all with just a black background.

Initially I just set the `image_url` option to an empty string which worked on my fire tablet but while trying to build a wallpanel using an rpi, I noticed that my ssh session would become unresponsive whenever wallpanel would activate. As soon as I deactivated wallpanel, my ssh session would be responsive again.
I'm not sure what's happening here but I have the feeling something is trying to fetch a resource constantly and keeps on failing.

For now I've uploaded a one pixel black image to my webserver and refered to it instead of leaving the `image_url` option empty.
This works and my ssh session stays responsive now.
However, I ocasionally  get a random wallpaper to show instead of my black background. Not sure why this is.

**Comment by j-a-n** [comment]
If you set the "image_url" option to an empty string, that should be fine.
I am not sure why this happens.
Please try version 4.10.2 where I added some additional checks to the image_url.

**Comment by LordMike** [comment]
Oh hey, the blank works.. I uploaded a black picture and everything.

Anyways, I can confirm a blank string for `image_url` works fine to make a black background. In wp `4.10.5`

**Comment by j-a-n** [comment]
Okay, fine, thanks for testing.

**Comment by tadly** [comment]
I currently can't test my specific issue because I'm unable to get a rpi setup up and running.
When time allowes it, I'll certainly test this and open another issue if there are still problems.

Sorry for the late respones. Really though I would be able to test this in time.

**Comment by j-a-n** [comment]
If there are still problems, the issue can be reopened.
