### ISSUE TITLE
Feature Request - Option to allow interaction with screensaver content

### ISSUE THREAD

**Issue by interestedcoder** [j-a-n/lovelace-wallpanel#104]
Currently, the content on the screensaver is, by design, not able to be interacted with: any touch or mouse click will deactivate the screensaver and bring you back to the underlying dashboard view where you can then interact. I'd love to be able to set an option that would keep the screensaver active to allow interaction e.g. turn the volume down on a media card without having to press once to end the screensaver and again to turn the volume down. Or tap the minimal weather icon that, via popup browser_mod, could popup onClick with more details of the current and future conditions. Etc. 

I could imagine this proposed feature to either require the use of a screensaver entity to manually control when when the screensaver is deactivated or, perhaps, the ability to define a rectangle of the screen that will always deactivate the screensaver with a tap e.g. 100px 100px in the bottom right corner. 

This integration + the ha-google-photos option is a gamechanger for me- incredible work on this and so greatly appreciated!

**Comment by j-a-n** [comment]
I think this is really a very nice feature.
I just released version 4.11.0 with experimental support for card interaction.
Please give it a try.
I am happy to receive feedback. 

To enable, simply set `card_interaction` to `true`.

**Comment by j-a-n** [comment]
Setting tap actions is fixed in 4.11.1

**Comment by kwithus** [comment]
Perfect! It now works as expected.
However, maybe you can assist me with the following challenge:
I placed a card on the screensaver, which navigates to another tab when tapped, that does work perfectly. 
However, once this tab is activated the screensaver is completely disabled, as this page is not in the list ‚enabled on tabs’, so I have to go back to the default page manually.
So I included the page into the ‘enabled on tab’ list, but then I can’t see the called tab, as the screensaver does not stop. ;-)
So, what I would like to do: when tapping on the card and by that navigate to another tab, the screensaver should stop and then start again after the idle timeout.
Any idea?
