### ISSUE TITLE
Hide Side Toolbar (Mobile Devices)

### ISSUE THREAD

**Issue by sumur1au** [j-a-n/lovelace-wallpanel#105]
The hide side toolbar function when enabled on mobile devices is not working. 

It is working for tablets or screens with larger resolutions.

**Comment by j-a-n** [comment]
Please test if version 4.10.3 resolves the issue.

**Comment by sumur1au** [comment]
Thanks, the icon is fixed. However if you have any notifications you can still see half of the blue circle.

**Comment by j-a-n** [comment]
Please test version 4.10.4.

**Comment by sumur1au** [comment]
Thanks @j-a-n it works perfectly. Much appreciated for all your hard work :)
