### ISSUE TITLE
Black toolbar in HA 2023.5 beta 

### ISSUE THREAD

**Issue by LukaszP2** [j-a-n/lovelace-wallpanel#106]
In new HA 2023.5b1 is black space were was toolbar (hide_toolbar: true)
 
![image](https://user-images.githubusercontent.com/44735995/235286720-2eefedb9-6a9c-4b30-b5b7-56cf822d72aa.png)

**Comment by j-a-n** [comment]
Should be fixed in [v4.10.4](https://github.com/j-a-n/lovelace-wallpanel/releases/tag/v4.10.4).
