### ISSUE TITLE
show photos from intern server

### ISSUE THREAD

**Issue by justinw78** [j-a-n/lovelace-wallpanel#107]
I don't think it's a bug but has more to do with my ignorance.

My homeassistant ip is 172.*.*.2  and the photo's are on a intern webserver 172.*.*.50. (subnet is the same )

My configuration is as follows:

wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  image_url: http://172.*.*.50/hassfoto/hassfoto
  show_progress_bar: true
  show_image_info: true
  image_order: random

In the directory from the image url are 2 photo's 1.jpg and 2.jpg. But it wont load them.  Do i need a specific file in the photo directory?   If i make the url:  http://172.*.*.50/hassfoto/hassfoto/1.jpg then that photo will load.

Can someone tell me what im doing wrong?

Greetings Justin

**Comment by j-a-n** [comment]
Wallpanel needs a list of images to go through. If you are using a simple web server like nginx or apache, there is no list of images to retrieve. If your web server has directory listings enabled (indexes), it would be possible to parse those listings and try to extract links to images. This is not trivial, as these directory listings are not standardized. This approach becomes even more complicated if you store your images in subdirectories. These subdirectories must then be searched recursively. A better solution would be to add a parsable (e.g. JSON format) index file to the web server that contains a listing of all available images. This file could then be fetched and parsed by wallpanel.

**Comment by justinw78** [comment]
Thnx for the Quick Reply!  
I have changed the strategy and made a mount from the other server to the media directory. 
Its now in /media/hassfoto.   
If i give the image url: /  it works but if i  do /hassfoto then it shows black pictures.  (not with an broken image picture left top)

But a little step further.  If you have an idea to get the right directory its verry welcome.

Greetings justin

**Comment by justinw78** [comment]
Also solved...  The link was /local/hassfoto.

So i close this:) 

Thnx for the explaining!

Greetings Justin
