### ISSUE TITLE
Camera entity instead of picture entity?

### ISSUE THREAD

**Issue by columnmn** [j-a-n/lovelace-wallpanel#109]
Hi. 

Loving the idea of the wall panel. It's exactly what I'm looking for.

I set up a album and hooked up Google photos to Hass. The entity that shows up the photos is a camera entity, rather than a picture entity. It's not showing them up, so I figure that's my issue.

Any work around for that?

Thanks!

**Comment by columnmn** [comment]
I tried that one already:
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  image_url: media-entity://camera.google_photos_dashboard_media
  cards: []

I'm just getting a broken image sign. The same entity is working fine in a card.
![unnamed-574x675](https://user-images.githubusercontent.com/123281386/236930036-bb5416cb-c115-4a74-b2c5-960aeed54df6.gif)

Same as that image, I can't screenshot it without the screensaver disappearing.

**Comment by j-a-n** [comment]
Hey @Daanoz, would you mind taking a look at this?

**Comment by Daanoz** [comment]
Sure, I'll have a look somewhere this week.

**Comment by columnmn** [comment]
Thanks! I apperciate it!

**Comment by kwithus** [comment]
For me this entry does work:

image_url: media-entity://camera.homeassistant_live
image_fit: scale-down

(Camera.homeassistant_live is the name of my camera entity)

**Comment by columnmn** [comment]
I'm not sure why, but I just retried it, and it's working! 

Thanks if anybody changed it!
