### ISSUE TITLE
time

### ISSUE THREAD

**Issue by marcolega** [j-a-n/lovelace-wallpanel#12]
can you provide an example to show date time as in the wiki picture?
![Screenshot_20220815-225805_Home Assistant](https://user-images.githubusercontent.com/97765943/184717293-35f623a0-9b37-48d6-8855-1efb2cc429f3.jpg)

**Comment by LukaszP2** [comment]
`  cards:
    - type: custom:digital-clock
      dateFormat:
        weekday: long
        day: 2-digit
        month: short
      timeFormat:
        hour: 2-digit
        minute: 2-digit`
