### ISSUE TITLE
Can´t edit yaml- help please

### ISSUE THREAD

**Issue by jiripaskov** [j-a-n/lovelace-wallpanel#124]
Hello, I enabled your very nice addon. My lovelace is now fullscreen. I can go to config using URL, but. I can´t edit lovelace to turn off your addon. Please could you help me how to turn off or edit your addon settings after it has been enabled? I mean I can´t reach lovelace yaml for editing from GUI and via file editor it is not accesible....

Thank you very much.

**Comment by jiripaskov** [comment]
It is possible using /lovelace/default_view?edit=1
Btw - can I prevent user from entering into this URL?

**Comment by j-a-n** [comment]
Hi, please see #72
