### ISSUE TITLE
Add scheduling of black screen.

### ISSUE THREAD

**Issue by justinwoodland** [j-a-n/lovelace-wallpanel#132]
Currently we have the ability to set `black_screen_after_time` which waits x time and then goes black. 

I would like to be able to configure 'black hours' for when everyone is asleep.

this could look like:
```
black_screen_scheduled_start_time: 17:00
black_screen_scheduled_end_time: 06:00
```
or 
```
black_screen_schedule: 17:00/06:00
```

**Comment by j-a-n** [comment]
I think, it would be better to use HA Automation and [Profiles](https://github.com/j-a-n/lovelace-wallpanel#profiles) for this. That way you would be more flexible in setting your "black hours".

**Comment by justinwoodland** [comment]
Thanks. I'll look into it.
