### ISSUE TITLE
local media don't work since the last update

### ISSUE THREAD

**Issue by detlefh68** [j-a-n/lovelace-wallpanel#135]
Since the last update, the images from local media are no longer loaded.

This is my image url, which worked fine:

 image_url: media-source://media_source/local/photo

**Comment by j-a-n** [comment]
Did you try to clear the browser cache?
Are there any errors in the browser console (F12)?

**Comment by detlefh68** [comment]
Yes I cleared the cache and tried different devices.
I use a fire DH 10 with fully kiosk browser and a Mac and found no possibility to activate the browser console, sorry.
I installed the version 4.15.0 and it works perfect.

**Comment by j-a-n** [comment]
Could you please post the complete wallpanel configuration?

**Comment by detlefh68** [comment]
yes I can:

wallpanel:
  enabled: true
  enabled_on_tabs:
    - home
    - wohnzimmer
    - esszimmer
    - kuche
    - flur
    - bad
    - wc
    - nordzimmer
    - schlafzimmer
    - terrasse
    - keller
    - flur-keller
    - wohnzimmer-erich
    - bad-keller
    - vorratsraum
    - heizungsraum
    - garage
    - photovoltaik
    - stromspeicher
  debug: false
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  show_images: true
  idle_time: 0
  display_time: 20
  profile_entity: input_select.fire_hd_tageszeit
  profiles:
    day:
      image_url: media-source://media_source/local/photo
      style:
        wallpanel-screensaver-container:
          background-color: '#333333dd'
        wallpanel-screensaver-info-box:
          '--wp-card-width': 150px
          background-color: '#ffffff33'
          box-shadow: >-
            0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
            0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
        wallpanel-screensaver-info-box-content:
          '--ha-card-background': none
          '--ha-card-box-shadow': none
          '--ha-card-border-width': 0px
          '--primary-background-color': '#fafafa'
          '--secondary-background-color': '#e5e5e5'
          '--primary-text-color': '#212121'
          '--secondary-text-color': '#727272'
        wallpanel-screensaver-image-info-exif:
          '--primary-background-color': '#fafafa'
          '--secondary-background-color': '#e5e5e5'
          '--primary-text-color': '#212121'
          '--secondary-text-color': '#727272'
          background-color: '#ffffff33'
    night:
      image_url: media-source://media_source/local/photo
      style:
        wallpanel-screensaver-info-box:
          '--wp-card-width': 150px
          background-color: '#00000033'
          box-shadow: >-
            0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
            0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
        wallpanel-screensaver-info-box-content:
          '--ha-card-background': none
          '--ha-card-box-shadow': none
          '--ha-card-border-width': 0px
          '--primary-background-color': '#111111'
          '--secondary-background-color': '#202020'
          '--primary-text-color': '#e1e1e1'
          '--secondary-text-color': '#9b9b9b'
        wallpanel-screensaver-image-info-exif:
          '--primary-background-color': '#111111'
          '--secondary-background-color': '#202020'
          '--primary-text-color': '#e1e1e1'
          '--secondary-text-color': '#9b9b9b'
          background-color: '#00000033'
  keep_screen_on_time: 0
  black_screen_after_time: 0
  control_reactivation_time: 1
  screensaver_stop_navigation_path: http://homeassistant.home.lan:8123/lovelace-wallpanel/home
  image_url: media-source://media_source/local/photo
  image_fit: contain
  image_list_update_interval: 3600
  image_order: random
  image_excludes:
    - \.tif$
    - /@eaDir
    - /Auftraege
    - /Foto-Anfragen
    - /Fotografen
    - /Fotoprojekte
    - /Fotos Anja
    - /Fotos Detlef
    - /Fotos Gaby
    - /Kinoverein Gandeon e.V*
    - /PhotoLibrary
    - /SCAN
    - /Share
    - /Test
  show_exif_info: true
  fetch_address_data: true
  exif_info_template: >-
    ${address.town|address.city!prefix=!suffix= //
    }${DateTimeOriginal!options=year:numeric,month:long}
  screensaver_entity: input_boolean.fire_hd_screensaver
  info_animation_duration_x: 0
  info_animation_duration_y: 0
  info_animation_timing_function_x: ease-in-out
  info_animation_timing_function_y: ease-in-out
  info_move_pattern: random
  info_move_interval: 0
  info_move_fade_duration: 2
  cards:
    - type: custom:digital-clock
      dateFormat:
        weekday: short
        day: 2-digit
        month: short
      timeFormat:
        hour: 2-digit
        minute: 2-digit

**Comment by j-a-n** [comment]
What exactly is not working?
`idle_time` is set to `0`, so the screensaver  will not activate.

**Comment by detlefh68** [comment]
V4.15 works fine, atfer updating to v.4.16 no pictures from the local media folder are displayed. I trigger the screensaver with the "screensaver_entity: input_boolean.fire_hd_screensaver" with an external motion detector automation.

**Comment by detlefh68** [comment]
If I use the idle_time to activate the screensaver, can I deactivate it with the entity?

**Comment by j-a-n** [comment]
Should be fixed in v4.17.0

**Comment by detlefh68** [comment]
Hi, the issue ist fixed, thank you :-)
