### ISSUE TITLE
Multiple media-entities

### ISSUE THREAD

**Issue by kristianschneider** [j-a-n/lovelace-wallpanel#137]
First of all: Great work.

Would it be possible to have multiple media entities?
I use the google photos integration and I am only able to display one album ie:

image_url: media-entity://camera.google_photos_an_album

**Comment by j-a-n** [comment]
Thanks!

Multiple media entries are not possible at the moment, but you can use [Dynamic configuration using entities](https://github.com/j-a-n/lovelace-wallpanel#dynamic-configuration-using-entities).
With this feature you can switch your `image_url` by an HA automation.
