### ISSUE TITLE
using the screensaver of this itergration suddenly quit the app after two hours

### ISSUE THREAD

**Issue by isaac1232011** [j-a-n/lovelace-wallpanel#139]
I found you integration is useful, and fit my need for the android wall tablet(samsung).However, when the screensaver start, everything work prefectly find,However, after two hours, the HA suddenly quit the anddroid.I have google this online, some said the screensaver occupiess lots of resources...I am not sure for this.

I just use the screensave to show windy graph, and some bus arrival time with the html
here are my dashbord setting

wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: true
  fullscreen: true
  idle_time: 30
  image_url: http://picsum.photos/${width}/${height}?random=${timestamp}
  image_fit: cover
  image_order: sorted
  show_image_info: false
  info_animation_duration_x: 30
  info_animation_duration_y: 11
  info_animation_timing_function_x: ease-in-out
  info_animation_timing_function_y: ease-in-out
  info_move_pattern: random
  info_move_interval: 0
  info_move_fade_duration: 2
  badges:
    - entity: sensor.temperature
      name: temperature
    - entity: sensor.index_exposure_level
      name: UV
  cards:
    - type: iframe
      url: /local/windy.html
      aspect_ratio: 80%
    - type: iframe
      url: /local/busArrival8.html
      aspect_ratio: 80%
    - type: custom:apexcharts-card
      show:
        last_updated: true
      header:
        standard_format: false
        show: true
        show_states: true
        colorize_states: true
        title:  electricity usage
      hours_12: false
      graph_span: 7d
      now:
        show: true
        label: Now
        color: red
      color_list:
        - green
        - blue
      series:
        - entity: sensor.clp
          type: line
          data_generator: |
            const now = new Date();
            return entity.attributes.daily.map((item, i) => {
              //return [now.getTime() - i * 1000 * 60 * 60, item.kwh];
              return [item.start, item.kwh];
            });
          show:
            name_in_header: false
            datalabels: true
      apex_config:
        dataLabels:
          enabled: true
          dropShadow:
            enabled: true
  style:
    wallpanel-screensaver-info-box:
      font-size: 7vh
      font-weight: 600
      color: '#eeeeee'
      text-shadow: >-
        -2px -2px 0 #03a9f4, 2px -2px 0 #03a9f4, -2px 2px 0 #03a9f4, 2px 2px 0
        #03a9f4
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      text-shadow: >-
        -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px
        0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'

**Comment by isaac1232011** [comment]
After removing the windy web page, the integration operate fine.I think the integration may have memory leak.If the webpage refresh less than 5 mins, it will occupy lots of tablet resource, and force the tablet quite the app.I have tried to make a work aroud to make an automation to switch off the tablet every 2 hours, but it is still not working...

**Comment by j-a-n** [comment]
Okay, doesn't seem to be related to the wallpanel addon.
