### ISSUE TITLE
image_list_update_interval for api.unsplash.com

### ISSUE THREAD

**Issue by DobrijZmej** [j-a-n/lovelace-wallpanel#144]
https://github.com/j-a-n/lovelace-wallpanel/blob/444344cb0b9a7834ed307be66f3098027b004ab3/wallpanel.js#L134
https://github.com/j-a-n/lovelace-wallpanel/blob/444344cb0b9a7834ed307be66f3098027b004ab3/wallpanel.js#L311-L314

Are you sure, that it should be 90?
3600 in config it is one hour, as I understand...

Maybe it should be compared with less then 90?
If user sets interval less then 90 seconds, then set in to 90.
``` js
		if (imageSourceType() == "unsplash-api" && config.image_list_update_interval < 90) {
			// Unsplash API currently places a limit of 50 requests per hour
			config.image_list_update_interval = 90;
		}
```

**Comment by j-a-n** [comment]
You are right, I will fix this in the upcoming version.
Thanks!
