### ISSUE TITLE
screensaver dosent start

### ISSUE THREAD

**Issue by ca1p3** [j-a-n/lovelace-wallpanel#145]
hi i cant get the screen saver to kick in i have set the idle time to 10 but nothing happens. im running the latest core and everything

**Comment by j-a-n** [comment]
Hello!
Please post your dashboard / wallpanel config

**Comment by ca1p3** [comment]
hi this is my config

wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 10
  display_time: 5
  image_url: media-entity://camera.google_photos_familjen_media
  select.image_selection_mode: Random
  image_fit: contain
views:

Den lör 26 aug. 2023 kl 13:27 skrev Jan Schneider ***@***.***

**Comment by j-a-n** [comment]
What device / browser are you using?
Could you try a very basic config, like:
```yaml
wallpanel:
  enabled: true
  fullscreen: false
  idle_time: 10
```

**Comment by ca1p3** [comment]
Somehow it all started to work again on all my devices dont know why i
didnt do anything

Den lör 26 aug. 2023 16:21Jan Schneider ***@***.***> skrev:
