### ISSUE TITLE
idle_time based on entity value

### ISSUE THREAD

**Issue by ian-tait** [j-a-n/lovelace-wallpanel#146]
Looking over the docs, I can't see away to make the idle_time a variable for the user to set. 

As I understand the idle_time can be set to '0' to disable the screensaver, but I can't see away to assign an entity. 

The docs suggest the following for a 5 second timeout:
`idle_time: 5`

but I would like the following for the user to choose the time out (which includes '0' so they can disable the screensaver):
`idle_time: input_number.screensaver_time_out`

It could be possible the is available already and I have missed it in the docs, so any pointers would be really helpful.

Thank you for a great bit of code. 

Ian

**Comment by j-a-n** [comment]
You can use [Dynamic configuration using entities](https://github.com/j-a-n/lovelace-wallpanel#dynamic-configuration-using-entities)

**Comment by j-a-n** [comment]
Were you able to resolve the problem?
