### ISSUE TITLE
Random info-box position

### ISSUE THREAD

**Issue by Superpiffer** [j-a-n/lovelace-wallpanel#15]
I'm trying to move the info-box in random position every minute, with a simple fade-out/fade-in (like the old version of this integration) but I'm not sure how to achieve this with animation-timing-function or if it's possibile.
Do you have an example for a simple animation like that?

**Comment by j-a-n** [comment]
This is difficult to achieve with pure CSS.
With version 2.5 of the addon there are two new configuration variables to make this possible:
```yaml
info_random_move_interval: 60
info_random_move_fade_duration: 2.0
```
