### ISSUE TITLE
Suggestion: Improve transparent style for better background protection

### ISSUE THREAD

**Issue by j9brown** [j-a-n/lovelace-wallpanel#150]
When using the transparent style recommended in the README, I found the text shadows to provide insufficient background protection in some cases.  I also noticed that icons and other elements could also be hard to see and looked a little out of place next to shadowed text.

So I played around with it a bit.  First I tried applying a drop-shadow filter to just the icons, then I realized I could remove the text shadow and apply a drop-shadow filter to the entire content.  Much simpler.

I actually ended up using two filters: one with a narrow radius to provide most of the contrast and a second one with a wider radius for a bit more background protection.  The content is much more readable and consistent now!

Anyhow, I thought this trick might be useful to other people and that it might be worth amending the README with something along these lines.  It took me a while to figure out it was even possible.

```
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'
      filter: 'drop-shadow(0px 0px 3px rgb(17, 17, 17)) drop-shadow(0px 0px 8px rgb(30, 30, 30))'
```

Cheers!

**Comment by ILiveInAHouse** [comment]
Yes this looks much better!  Thanks!

**Comment by j-a-n** [comment]
Thanks!
I just added the style to the documentation.
