### ISSUE TITLE
New image_background setting is not working in Android companion app

### ISSUE THREAD

**Issue by stiw47** [j-a-n/lovelace-wallpanel#151]
First, thanks for this.

As the title says, `image_background` is not working in Android app.
When `image_background: image` setting is applied, borders stay black instead to become blurred current image.
Tried to clear cache of HA Android companion app several times on two devices. On one of these two devices I also cleared app data and signed in to HA again.
It is also not working from the Chromium browser on Android (maybe other browsers too)
It is working as expected in Firefox browser on desktop PC.
Nothing urgent, even less important, just to let you know.
Below is my conf:

```
wallpanel:
  enabled: true
  fullscreen: false
  hide_sidebar: false
  hide_toolbar: false
  debug: false
  image_url: /media/family
  image_fit: contain
  image_background: image
  image_order: random
  screensaver_stop_navigation_path: null
  idle_time: 15
  display_time: 10
  card_interaction: true
  info_animation_duration_x: 30
  info_animation_duration_y: 13
  info_animation_timing_function_x: ease-in-out
  info_animation_timing_function_y: ease-in-out
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
      background-color: '#00000066'
      box-shadow: 0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-background-color': '#111111'
      '--secondary-background-color': '#202020'
      '--primary-text-color': '#e1e1e1'
      '--secondary-text-color': '#9b9b9b'
  cards:
    - type: custom:digital-clock
    - type: weather-forecast
      entity: weather.openweathermap
      show_forecast: true
      #theme: kibibit

  badges:
    - entity: person.aleksandra
    - entity: person.mikri_maus
```

**Comment by j-a-n** [comment]
It is working on my Android devices in the Companion app.
Which Android / Chromium version are you using?

**Comment by stiw47** [comment]
Unfortunately, both of them are shi*y 😁, so maybe could be performance issue as well?

First one is wall tablet, Lenovo TB-8505X with official firmware, not rooted, and Android 10. HA Companion is latest one, 2023.9.2-full

Second one is even worse, Samsung J7 2016 (SM-J710F), rooted, with crDroid custom ROM, Android 10. Companion app is the same version, 2023.9.2-full, Chromium is latest version from [here](https://github.com/uazo/bromite-buildtools).

HA companion app data wipe was performed on tablet, while on phone I done just several app cache wipes.

**Comment by j-a-n** [comment]
No, everything is rendered on the client.
I will try to find an old android device to reproduce the issue.

**Comment by j-a-n** [comment]
Unfortunately, I can't afford to test all the features on old android versions. I am therefore closing the issue. If anyone wants to contribute changes for older devices, please feel free to open a pull request.
