### ISSUE TITLE
Delay of 5s before returning to dashboard

### ISSUE THREAD

**Issue by AlenHodnik** [j-a-n/lovelace-wallpanel#157]
Having problem with wallpanel addon. Everything works fine, except when I tap on a screen to return to dashboard, it takes randomly from 5-8s to return to it.

Tried with different browsers, fully kiosk, wallpanel, ... same results. Tried with almost empty dashboard to see if cards are problem, but same. 

Fire tablet 10 pro tablet.

**Comment by Bort89** [comment]
Have you tried on a different device? Here it is slow sometimes because of the device we are using.

**Comment by j-a-n** [comment]
Seems to be a problem with the device.
No way to fix the problem in the wall panel.
