### ISSUE TITLE
Feature request: Make image_path templatable

### ISSUE THREAD

**Issue by Vedeneb** [j-a-n/lovelace-wallpanel#161]
It would be nice if the `image_path` could be made templatable with HA entities. I display family photos which are stored on our NAS and are accessed locally using a media source. It's thousands of photos and most of them are stored as year/month (e.g. 2013/04) so my `image_path` for this folder would be `/digitalkamera/2013/04`. Instead of hard coding this to the lovelace config, I would like to be able to add entity_ids as placeholders, so the screensaver could show photos of a different month each day.
So my `image_path` could look something like this: `/digitalkamera/{{ states('sensor.photos_year') }}/{{ states('sensor.photos_month') }}`. And I would have automations to update this sensors ad midnight or something like that.

Or, alternatively, build the whole `image_path` in HA so whenever a sensor entity is provided (instead of an url), it uses the current state of this sensor as `image_path`, i.e. `image_path: sensor.my_image_path`. I guess this would be easier to implement.

**Comment by j-a-n** [comment]
This is already possible.
Please have a look at #154 and https://github.com/j-a-n/lovelace-wallpanel#dynamic-configuration-using-entities

**Comment by Vedeneb** [comment]
Thank you!!
Not sure how I missed that, sorry.
