### ISSUE TITLE
Feature request: Previous image when tapping on the left

### ISSUE THREAD

**Issue by Vedeneb** [j-a-n/lovelace-wallpanel#162]
While it's already possible to move to the next image when tapping on the right, it would be great to also go back to the previous image when tapping on the left. This is especially useful when displaying family photos and someone wants to show a special photo to someone else. Usually until they are ready the photo is already gone :-)

**Comment by j-a-n** [comment]
This is now implemented in version 4.23.0.

**Comment by labaland** [comment]
> This is now implemented in version 4.23.0.

Just got here to ask why the image changes when tapping on both sides of the screen, sometimed i have to tap it multible times to close the screensaver. This might be the reason then XD
