### ISSUE TITLE
Play only files filter

### ISSUE THREAD

**Issue by ikolsteren** [j-a-n/lovelace-wallpanel#163]
Currently I am playing all the photos off my NAS.  I haven't gone through them all to delete really bad ones but have flagged them with metadata flags. 
Would be nice to be able to filter on tags and only play starred files etc.

**Comment by j-a-n** [comment]
Yes, would be a nice feature but unfortunately, this image metadata is not available in Home Assistant.
If this is ever possible in the future, the issue is welcome to be reopened.
