### ISSUE TITLE
Feature Request: Idle Time Templateable

### ISSUE THREAD

**Issue by teek541** [j-a-n/lovelace-wallpanel#165]
Hey guys, I'm wondering if it's possible to set an idle time based on a template?  I couldn't get it to work, and figured it may not be allowed as I didn't see it in the documentation.

My specific use case for this being dynamic is for alarm control panels in my garage.  I have my shop being controlled by HA and I monitor the Air Quality while I'm working in there (later I want to show dust collection routing when I get that implemented).  However, when the shop alarm is disarmed (I'm working in there), I don't want wall panel to be active.  I was going to set idle time to 0 in that case.  If the shop is alarmed then I'm not using the tools and I don't need to monitor air quality and other states of tools in the shop.

**Comment by teek541** [comment]
Don't you love it when you answer your own question?
You can do it by setting it via an entity.  In this case an input_number.  However, I really wish that I could do it from a template and not have to create another helper.

Also, is there an easy way to wake the wallpaper from an entity?  Setting idle time to 0 after the wallpanel is active doesn't wake it up.

**Comment by j-a-n** [comment]
Please have a look at #167
