### ISSUE TITLE
HA 2023.11.b0 - dont work

### ISSUE THREAD

**Issue by LukaszP2** [j-a-n/lovelace-wallpanel#168]
I just install beta HA 2023.11 and WP stop working ;/ Has any one test it jet?

**Comment by LukaszP2** [comment]
There will be fix for that in 2023.11.0.b1

**Comment by LukaszP2** [comment]
There will be fix for that in 2023.11.0.b1

**Comment by zyphlar** [comment]
Not seeing any sort of screensaver or activity on HA 2023.11.2 with WP 4.22.1 (Firefox, Windows) -- network inspector shows it's grabbing the images, just not displaying anything.

**Comment by zyphlar** [comment]
Nevermind after reloading like 5 times and navigating around and forgetting about it somehow it's decided to work now even though I did nothing different
