### ISSUE TITLE
Screensaver not starting on Android

### ISSUE THREAD

**Issue by hawkeye100** [j-a-n/lovelace-wallpanel#169]
Screensaver does not start on Android 6 or 13 (tablet and phone) but does start on Linux tablet in browser (even though it shows as error in log - see below). Some other features do work (hide left/top menu/toolbar).

Debug does not show on Android either. 

[HA: OS 10.5, Core 2023.9 Wallpanel 4.18.]

Described in more detail here: https://community.home-assistant.io/t/wallpanel-addon-wall-panel-mode-for-your-home-assistant-dashboards/449857/216?u=hawk100

Similar to #164 _**but not the same**_ as not solved with restart/reboot of either server or tablet/phone.

Log shows:
`Logger: frontend.js.latest.202309110
Source: components/system_log/__init__.py:269
First occurred: 25 October 2023 at 23:01:11 (8616 occurrences)
Last logged: 15:31:08

Uncaught error from Chrome WebView 117.0.0.0 on Android 13 TypeError: Cannot read properties of null (reading 'cloneNode') WallpanelView.restartProgressBarAnimation (/hacsfiles/lovelace-wallpanel/wallpanel.js:1143:25) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:1866:8) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:732:10)
Uncaught error from Chrome WebView 95.0.4638.74 on Android 6.0.1 TypeError: Cannot read properties of null (reading 'cloneNode') HTMLElement.restartProgressBarAnimation (/hacsfiles/lovelace-wallpanel/wallpanel.js:1143:25) HTMLElement.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:1866:8) HTMLElement.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:732:10)
Uncaught error from Chrome WebView 95.0.4638.74 on Android 6.0.1 Script error. null @:0:0
Uncaught error from Chrome WebView 118.0.0.0 on Android 13 TypeError: Cannot read properties of null (reading 'cloneNode') WallpanelView.restartProgressBarAnimation (/hacsfiles/lovelace-wallpanel/wallpanel.js:1143:25) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:1866:8) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:732:10)
Uncaught error from Chrome 114.0.0.0 on Linux x86_64 TypeError: Cannot read properties of null (reading 'cloneNode') WallpanelView.restartProgressBarAnimation (/hacsfiles/lovelace-wallpanel/wallpanel.js:1143:25) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:1866:8) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:732:10)`

Any help gratefully received, especially if I have missed something, in which case apologies in advance.

**Comment by hawkeye100** [comment]
Switching off the progress bar appears to act as a workaround resolution.

**Comment by j-a-n** [comment]
Please try if version 4.19.0 fixes the issue.

**Comment by hawkeye100** [comment]
Thanks. Updated via HACS.

Same behaviour as before I am afraid (works on Linux laptop, despite showing error), but no screensaver on Android 6 nor 13.

My wallpanel config is in case it helps):

> wallpanel:
  enabled: true
  debug: false
  hide_toolbar: false
  hide_sidebar: true
  fullscreen: false
  idle_time: 10
  display_time: 60
  show_progress_bar: true
  image_url: https://source.unsplash.com/random/1900x1200?beige,drone&random=${timestamp}
  image_fit: cover
  fade_in_time: 1
  screensaver_stop_navigation_path: /dashboard-mobile/0
  info_move_pattern: corners
  info_move_interval: 14
  info_move_fade_duration: 2
  image_list_update_interval: 300
  style:
    wallpanel-screensaver-container:
      background-color: '#333333dd'
    wallpanel-screensaver-info-box:
      '--wp-card-width': 250px
      background-color: '#fff8dc99'
      box-shadow: >-
        0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
        0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-background-color': '#fafafa'
      '--secondary-background-color': '#e5e5e5'
      '--primary-text-color': '#212121'
      '--secondary-text-color': '#727272'
  cards:
    - type: custom:clock-card
      time_zone: Europe/London
      size: 200
      font_size: 30
      disable_seconds: false
      display_date: DDD D MMMM
      theme:
        background: khaki
        hands: sienna
        numbers: sienna
        border: khaki
views:
  - title: Home

**Comment by hawkeye100** [comment]
Thanks. Updated from HACS to 4.19 (checked and confirmed)

Sorry, but still the same behaviour (working on Linux laptop despite showing a HA error, but not on Android 6 nor 13)

Switching progress bar off for now (not a deal breaker for me, but would be nice to have if that help with resolution priority)

Log:

`Logger: frontend.js.latest.202309110
Source: components/system_log/__init__.py:269
First occurred: 12:45:36 (350 occurrences)
Last logged: 12:59:16

Uncaught error from Chrome WebView 118.0.0.0 on Android 13 TypeError: Cannot read properties of null (reading 'replaceChild') WallpanelView.restartProgressBarAnimation (/hacsfiles/lovelace-wallpanel/wallpanel.js:1143:40) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:1877:8) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:732:10)
Uncaught error from Chrome WebView 95.0.4638.74 on Android 6.0.1 TypeError: Cannot read properties of null (reading 'cloneNode') HTMLElement.restartProgressBarAnimation (/hacsfiles/lovelace-wallpanel/wallpanel.js:1143:25) HTMLElement.switchActiveImage (/hacsfiles/lovelace-wallpanel/wallpanel.js:1813:8) HTMLElement.updateScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:1968:11) HTMLElement.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:728:9)
Uncaught error from Chrome 114.0.0.0 on Linux x86_64 TypeError: Cannot read properties of null (reading 'replaceChild') WallpanelView.restartProgressBarAnimation (/hacsfiles/lovelace-wallpanel/wallpanel.js:1143:40) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:1877:8) WallpanelView.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:732:10)`

wallpanel config (in case it helps):

wallpanel:
  enabled: true
  debug: false
  hide_toolbar: false
  hide_sidebar: true
  fullscreen: false
  idle_time: 10
  display_time: 60
  show_progress_bar: true
  image_url: https://source.unsplash.com/random/1900x1200?beige,drone&random=${timestamp}
  image_fit: cover
  fade_in_time: 1
  screensaver_stop_navigation_path: /dashboard-mobile/0
  info_move_pattern: corners
  info_move_interval: 14
  info_move_fade_duration: 2
  image_list_update_interval: 300
  style:
    wallpanel-screensaver-container:
      background-color: '#333333dd'
    wallpanel-screensaver-info-box:
      '--wp-card-width': 250px
      background-color: '#fff8dc99'
      box-shadow: >-
        0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
        0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-background-color': '#fafafa'
      '--secondary-background-color': '#e5e5e5'
      '--primary-text-color': '#212121'
      '--secondary-text-color': '#727272'
  cards:
    - type: custom:clock-card
      time_zone: Europe/London
      size: 200
      font_size: 30
      disable_seconds: false
      display_date: DDD D MMMM
      theme:
        background: khaki
        hands: sienna
        numbers: sienna
        border: khaki
views:
  - title: Home

**Comment by j-a-n** [comment]
Please try if version 4.20.0 fixes the issue.

**Comment by hawkeye100** [comment]
Hi - thanks. 4.20 seems to fix it for Android 13, but not Android 6.

TBH given Android 6 is quite old (as is the tablet) then I can live without the progress bar there and I would quite understand if you specified a minimum android version >6 for wallpanel progress bar, to minimise your efforts to sort this out and let you focus on other issues or improvements.

I do not have Android 7, 8,etc to test at which point it might work. Another user reports 4.19 working with Android 11 (see [discussion](https://community.home-assistant.io/t/wallpanel-addon-wall-panel-mode-for-your-home-assistant-dashboards/449857/226?u=hawk100) linked in original post).

Thanks again for your work on this project.

**Comment by j-a-n** [comment]
Okay, thanks for the feedback.
I will not fix the progress bar for Android 6.
