### ISSUE TITLE
WallPanel won't work on older iPad Air

### ISSUE THREAD

**Issue by sommattlier** [j-a-n/lovelace-wallpanel#170]
WallPanel will not initiate on iPad Air Gen 1 (iOS 12.5.7) in browser or HASS iOS app including hiding sidebar, fullscreen, photos, etc. Works as expected on iPad Pro 11", iPad Pro 12.9", iPhone 15 Pro, and other devices. Tried many config changes and manual URL enable. WP worked on the iPad Air for at least 6 months; issue began a couple months ago, presumably with a HASS or WP update.

**Comment by GaetanUT1** [comment]
Hello, maybe same issue as this : [https://github.com/j-a-n/lovelace-wallpanel/issues/153](https://github.com/j-a-n/lovelace-wallpanel/issues/153)

**Comment by questionmarc1974** [comment]
I have the same issue...works on newer ios though, but this iPad air is not being updated anymore.

**Comment by j-a-n** [comment]
Please try if version v4.20.0 fixes the issue.

**Comment by sommattlier** [comment]
Yep that did it! Thanks so much!
