### ISSUE TITLE
Login attempt or request with invalid authentication from 192.168.1.1

### ISSUE THREAD

**Issue by cataseven** [j-a-n/lovelace-wallpanel#174]
Hi,

After the update, getting this error

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:129
Integration: HTTP (documentation, issues)
First occurred: 12:55:58 (3 occurrences)
Last logged: 12:56:12

Login attempt or request with invalid authentication from 192.168.1.1 (192.168.1.1). Requested URL: '/media/day/K1__1330.jpg?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2YTliOGRhNTAzZjc0ZjY5OWM0ZmU2NzBiNjJjODIxZCW10sImlhdCI6MTY5OTI2NDQzOSwiZXhwIjoxNjk5MjY0NDk5fQ.5BNUxzBPRaEx7wdlbD8ivNwc00Fm6tQRn9-SypOAoQo'. (Mozilla/5.0 (Linux; Android 13; SM-T733 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from 192.168.1.1 (192.168.1.1). Requested URL: '/media/day/K1__1331.jpg?authSig=eyJhbGciOiR5cCI6IkpXVCJ9.eyJpc3MiOiI2YTliOGRhNTAzZjc0ZjY5OWM0ZmU2NzBiNjJjODIxZCIsInBhdGg6W10sImlhdCI6MTY5OTI2NDQ1MywiZXhwIjoxNjk5MjY0NTEzfQ.k5I5iVGYoB4ZC5KT3ft3zouj34GsrKJe7_hcIOjYHpA'. (Mozilla/5.0 (Linux; Android 13; SM-T733 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from 192.168.1.1 (192.168.1.1). Requested URL: '/media/day/K1__1570.jpg?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eVkaWEvZGF5L0sxX18xNTcwLmpwZyIsInBhcmFtcyI6W10sImlhdCI6MTY5OTI2NDQ2OCwiZXhwIjoxNjk5MjY0NTI4fQ.6iIwFTxXalJ1CYNvkOViG-zgmM1EnR1gVaLDW6TmAjg'. (Mozilla/5.0 (Linux; Android 13; SM-T733 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Safari/537.36)

**Comment by j-a-n** [comment]
Please clear browser cache and try again.

**Comment by cataseven** [comment]
> Please clear browser cache and try again.

Try solution but still getting the same error

**Comment by j-a-n** [comment]
Please try version 4.22.0, thanks!

**Comment by j-a-n** [comment]
Seems to be fixed, if not, please open again.
