### ISSUE TITLE
Weather-Forecast Card Issue in Wall Panel

### ISSUE THREAD

**Issue by venuveera** [j-a-n/lovelace-wallpanel#179]
I added the weather forecast card to the cards section of my wall panel. The card displays correctly when the screen saver is activated, but there is an issue with the fonts. The minimum temperature appears in bold and large font, while the maximum temperature appears in a smaller font. However, the same card with the same lines displays correctly under the Home Assistant views section.
![WallPanelIssue](https://github.com/j-a-n/lovelace-wallpanel/assets/5315390/3b16bf06-2309-40c3-99b7-823d4dafbdb2)
![HomeAssistantView](https://github.com/j-a-n/lovelace-wallpanel/assets/5315390/eca70308-2df7-4fa5-9995-6b4e01ed3861)

This is the code
```
wallpanel:
  enabled: false
  debug: false
  hide_toolbar: true
  hide_toolbar_action_icons: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 40
  screensaver_stop_navigation_path: /fire-tablet-10/default_view
  image_url: >-
    https://source.unsplash.com/random/${width}x${height}?pleasant&sig=${timestamp}
  image_fit: cover
  image_list_update_interval: 3600
  image_order: sorted
  image_excludes: []
  card_interaction: true
  cards:
    - type: weather-forecast
      entity: weather.home
      show_forecast: true
  style:
    wallpanel-screensaver-info-box:
      font-size: 4vh
      font-weight: 600
      color: '#eeeeee'
      text-shadow: >-
        -2px -2px 0 #03a9f4, 2px -2px 0 #03a9f4, -2px 2px 0 #03a9f4, 2px 2px 0
        #03a9f4
views:
  - title: Home
    path: default_view
    cards:
      - type: weather-forecast
        entity: weather.home
        forecast_type: daily
```

**Comment by venuveera** [comment]
This is the code I am using 
` 
wallpanel:
  enabled: false
  debug: false
  hide_toolbar: true
  hide_toolbar_action_icons: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 40
  screensaver_stop_navigation_path: /fire-tablet-10/default_view
  image_url: >-
    https://source.unsplash.com/random/${width}x${height}?pleasant&sig=${timestamp}
  image_fit: cover
  image_list_update_interval: 3600
  image_order: sorted
  image_excludes: []
  card_interaction: true
  cards:
    - type: weather-forecast
      entity: weather.home
      show_forecast: true
  style:
    wallpanel-screensaver-info-box:
      font-size: 4vh
      font-weight: 600
      color: '#eeeeee'
      text-shadow: >-
        -2px -2px 0 #03a9f4, 2px -2px 0 #03a9f4, -2px 2px 0 #03a9f4, 2px 2px 0
        #03a9f4
views:
  - title: Home
    path: default_view
    cards:
      - type: weather-forecast
        entity: weather.home
        forecast_type: daily
`

**Comment by j-a-n** [comment]
You added some CSS style, which modifies the font:
> ```
> wallpanel:
>   style:
>     wallpanel-screensaver-info-box:
>       font-size: 4vh
>       font-weight: 600
>       text-shadow: >-
        -2px -2px 0 #03a9f4, 2px -2px 0 #03a9f4, -2px 2px 0 #03a9f4, 2px 2px 0
        #03a9f4
> ```

**Comment by venuveera** [comment]
Thanks, yes, you are right, removing the font size makes it the same, but when I add font size in the info box, it does that. How I could get a bigger font in the info box?

**Comment by j-a-n** [comment]
Perhaps you can use transform scale?:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-box:
      transform: scale(2)
      text-shadow: >-
      -2px -2px 0 #03a9f4, 2px -2px 0 #03a9f4, -2px 2px 0 #03a9f4, 2px 2px 0
       #03a9f4
```

**Comment by VeeGit09** [comment]
Thanks, scaling works, but it scales the white spaces as well and the whole card is scaled up.  The font size works just on the fonts.  It would be nice if there is a way to increase the font size for the weather card without the issue shown earlier.

**Comment by venuveera** [comment]
@j-a-n Thanks, scaling works, but it scales the white spaces as well and the whole card is scaled up. The font size works just on the fonts. It would be nice if there is a way to increase the font size for the weather card without the issue shown earlier.

**Comment by j-a-n** [comment]
Unfortunately, there is no way to better customize the style of the Weather Forecast card.
Perhaps you can find another custom weather forecast card that is more flexible.

**Comment by venuveera** [comment]
@j-a-n Got it, thanks.  Do you have any suggestions on a flexible weather forecast card?  If not, no worries.

**Comment by j-a-n** [comment]
Sorry, nothing I could recommend.
