### ISSUE TITLE
Enabled command not working 

### ISSUE THREAD

**Issue by aasaflo** [j-a-n/lovelace-wallpanel#183]
everything working well just with browser command. ?wp_enabeld=true otherwise nothing happen I tried on browser and tablet and ios app i tried the command enabled as true or as false same result

**Comment by j-a-n** [comment]
Please post your dashboard config yaml.

**Comment by aasaflo** [comment]
Thanks jan 
The problem is resolved by change command ”mode” in configuration.yaml file from “yaml”to “storage”
![Uploading image.jpg…]()


mode: yaml ——> mode: storage 👍🏻

**Comment by j-a-n** [comment]
Okay, fine 👍
