### ISSUE TITLE
1px white border on android webview

### ISSUE THREAD

**Issue by mattmon** [j-a-n/lovelace-wallpanel#184]
When using wallpanel on android webview, I'm getting a 1px white border on the left side of the screen.

![screencap](https://github.com/j-a-n/lovelace-wallpanel/assets/924673/4e20aa2a-5ceb-49e6-a60c-ad35be05ac35)

It does not seem to happen on Desktop browsers, but any android application using wallpanel with 'hide sidebar' eneabled  seem to exhibit the issue. (I've tested the HA app, fully kiosk and wallpanel browser)

Is there an easy [style fix](https://github.com/j-a-n/lovelace-wallpanel/issues/111) for this?

**Comment by mattmon** [comment]
Updating the system webview to something less ancient fixed the issue.

Please close.

**Comment by mattmon** [comment]
see the binaries [here](https://android.googlesource.com/platform/external/chromium-webview/+/bd0d83408049c849c28ce45c5175aa1bf2b991a5)

**Comment by j-a-n** [comment]
Please try if v4.23.1 fixes the issue.

**Comment by mattmon** [comment]
Not fixed for me on the old webview; but who cares.

However, all is well with a modern webview (v116 is what I used)

I can't confirm the report about safari, tested on an iPad and it works fine.

**Comment by Ramias1** [comment]
Currently traveling but will have an answer for you in a few days re IPad Kiosk Pro and Fully Kiosk on Fire tablets.

**Comment by Ramias1** [comment]
Can now confirm this is fixed for not my Fire Tablets and IPad.  Thanks for the great work on this.

**Comment by j-a-n** [comment]
Seems to be fixed, if not, please open again.
