### ISSUE TITLE
Image URL - Allow Templating or Entity 

### ISSUE THREAD

**Issue by Scoobler** [j-a-n/lovelace-wallpanel#188]
I’m currently using the unsplash URL with a search term, but would like to easily change the search term, I’ve tried templating, and passing an entity - neither worked.
It would be great if you could pass a text entity, that could be a ‘built’ URL, or if templating was possible that would work too.

**Comment by j-a-n** [comment]
Hi,
this is already possible:
https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#dynamic-configuration-using-entities

**Comment by Scoobler** [comment]
Amazing!!

Thanks for the hard work @j-a-n 

I’d read through the image_url section, but hadn’t looked at the dynamic configuration section!
