### ISSUE TITLE
Photo from Google Drive

### ISSUE THREAD

**Issue by cataseven** [j-a-n/lovelace-wallpanel#19]
Hi,

I have a shared link from my drive folder. Anyone with the link can see the folder. However I couldn't get the pictures. 

I also tried to add this to my config.yaml

```
homeassistant:
  allowlist_external_urls:
    - "MY_DRIVE LINK"
```

Any chance to reach this folder?

**Comment by j-a-n** [comment]
Not from wallpanel directly.
Perhaps you can use something like rclone to sync files from Google drive to a local HA media folder?

**Comment by swiergot** [comment]
I can confirm it's quite easy to set up rclone to download from Google Photos.

One of possible ways to do it is a separate container. Example Dockerfile:

```
FROM archlinux
RUN pacman -Sy
RUN pacman -S --noconfirm cronie rclone
RUN mkdir -p /root/.config/rclone
COPY rclone.conf /root/.config/rclone
RUN /bin/bash -c "echo '0 * * * * root /usr/sbin/rclone sync gphotos:/album/AlbumName /media/images' > /etc/cron.d/rclone"
VOLUME /media
CMD /usr/bin/crond -n
```

Put rclone.conf (must be created with `rclone config`) next to Dockerfile and run `docker build -t rclone .`.
