### ISSUE TITLE
Pop up from Browser mod

### ISSUE THREAD

**Issue by mellowism** [j-a-n/lovelace-wallpanel#192]
I would like the screensaver to remain active while displaying a popup on top of it. Is this doable? Additionally, I want the popup to automatically close after a set duration or to include a dismiss button that can be clicked without interrupting the screensaver's operation.

**Comment by j-a-n** [comment]
You can play around with the configuration of `z_index`.
The default value is `1000`, so that the popup is covered by the wallpanel.
Try setting it to a lower value:
```
wallpanel:
  z_index: 5
```
