### ISSUE TITLE
Feature request: Wallpanel enabled on a per user base

### ISSUE THREAD

**Issue by CyberLine** [j-a-n/lovelace-wallpanel#193]
In combination with https://github.com/breakthestatic/hass-sidebar-swipe i can use all my dashboards on my wallmounted tablet.
But if i start with the URL parameter, this will be gone after i use the navigation on the sidebar.

Would be really cool if i can just enable wallpanel for a user so that it works on all dashboards even when browsing around.

**Comment by j-a-n** [comment]
That is already possible:
https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#profiles

**Comment by CyberLine** [comment]
Ah nice. From my own rtfm dept ^^

Will give it a try. Thx.
