### ISSUE TITLE
input_boolean to stop screensaver not working

### ISSUE THREAD

**Issue by Cyclone47** [j-a-n/lovelace-wallpanel#194]
Hello,

I am trying to stop my screensaver using the input_boolean method. However; the screensaver won't start nor stop when toggling it.

**Configuration:**

wallpanel:
  **screensaver_entity: input_boolean.wallpanel_screensaver**
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  hide_toolbar_action_icons: true
  fullscreen: true
  idle_time: 60
  display_time: 30
  show_progress_bar: false
  image_url: >-
    https://source.unsplash.com/random/1920x1200?Netherlands,Nature&sig=${timestamp}
  image_fit: cover
  fade_in_time: 1
  profiles:
    user.xxxxx:
      enabled: false

**And automation:**

service: input_boolean.toggle
data: {}
target:
  entity_id: input_boolean.wallpanel_screensaver

Any advise?

**Comment by j-a-n** [comment]
Did you try to toggle `input_boolean.wallpanel_screensaver` manually?

**Comment by Cyclone47** [comment]
> Did you try to toggle `input_boolean.wallpanel_screensaver` manually?
Hi, thank you and apologies for my late response. I have managed to get it working by running: 

code: document.querySelector("home-assistant").shadowRoot.querySelector("home-assistant-main").shadowRoot.querySelector("wallpanel-view").stopScreensaver();
browser_id: xxxxxxx-xxxxxxx
