### ISSUE TITLE
NSPanel Pro & Fully Kiosk Motion Deection

### ISSUE THREAD

**Issue by pacmac** [j-a-n/lovelace-wallpanel#202]
See my post here: https://community.home-assistant.io/t/nspanel-pro-custom-android-apps-working/459563/198?u=crankshaft

has anybody figured out how to get the NSPanelPro's prescence detection to work with the wallpanel screensaver and stop the screensaver when presence is detected.

The presence detection is working, and should be passed to FullyKiosk since it is the Launcher for Fully App.

Any suggestions / solutions really appreciated

Thanks

PeterC

**Comment by pacmac** [comment]
OK, seems nobody else is doing this.

Trying to find work arounds now.

1) Is it possible to enable the screensaver via url query ? - I am thinking that I can use the fully screensaver http link, to enable the wallpanel screen saver ?

2) if not Is it possible to create a hidden card or lovelace tab that is formatted in the same style as the wallpanel screensaver and call that from fully kiosk.

**Comment by pacmac** [comment]
Fully Kiosk does send the screen off / screen on state to the home assistant switch, but it appears that this is only polled maybe every 30 secs as when the screen goes either on or off, it takes up to 30 seconds for the switch to be triggered in HA.

If this was real-time then my existing automation which switches the wallpanel screensaver boolean would be fine, but now when the screen is blanked and the wallpanel screensave is active, I can wake the display my movement, but the wallpanel screensaver only stops after some time and not immediately requiring a touch on the screen to switch it off.

**Comment by pacmac** [comment]
another update, I just enabled the MQTT feature of FK, and can confirm that it is only polling once a minute and there appears no option to increase this polling.

**Comment by j-a-n** [comment]
I don't know much about Fully Kiosk.
You could perhaps set something like `https://<ha-address>/lovelace/default_view?wp_idle_time=1` as the screensaver URL.
With `wp_idle_time=1` the screensaver would then start after one second.

**Comment by pacmac** [comment]
Thanks so much for the quick response.

Tried that option and it's not usable, because it reloads the entire app each time the screensaver kicks in.

**Comment by j-a-n** [comment]
How about using a webhook https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger?
You could use a webhook URL as the Fully screensaver URL.
The webhook automation could then switch the wallpanel screensaver.

**Comment by pacmac** [comment]
Thanks for helping, hang on, I think I have discovered something, will update here when I confirm.

**Comment by pacmac** [comment]
> How about using a webhook https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger? You could use a webhook URL as the Fully screensaver URL. The webhook automation could then switch the wallpanel screensaver.

Thanks, unfortunately that wont work as fully kiosk will display that webhook page.

What I have discovered is that the screenOff and screenOn events are fired in real time, I was subscribed to the stats which only updates once a minute, and that's also what the fullyKiosk HA integration uses which is why the display on switch does not change in real time in HA when the screen switches.

Solution was to create 2 MQTT sensors, one monitoring the screenOn event and the other the screenOff event and then combine them using a template sensor. then I use an automation that triggers on that template sensor to trigger the wallpanel screensaver.

It works, but ONLY when the screen is blanked, so when blanked and motion is detected, when the screen comes back on the screensaver will be off, but the motion sensor will not switch off the wallpanel screensaver unless the screen is blanked, so not really a good solution.

I think that FK does not pass the presence event back to webview, if it did then the wallpanel screensaver would trigger off as expected. I have sent a request to FK to investigate / add this event, but I dont hold out much hope.

Thanks so much for your help

**Comment by pacmac** [comment]
OK, After help from FK support, I think I may have a solution, you can enable the device's sensors and inject code to read the value. There's no event unfortunately which means that you have to poll it which is very inefficient:

```
setInterval(() => { fully.getSensorValue(8) > 250 && document.dispatchEvent(new TouchEvent('touchstart', { bubbles: true, cancelable: true, view: window, clientX: -100, clientY: -100 })); }, 1000);
```

Is there a javscript call that I can make to stop the screensaver as creating a touch event as above just triggers wallpanel screensaver to load the next image ?

**Comment by pacmac** [comment]
OK, got it:

`setInterval(() => { fully.getSensorValue(8) > 250 && document.querySelector("home-assistant").shadowRoot.querySelector("home-assistant-main").shadowRoot.querySelector("wallpanel-view").stopScreensaver(); }, 1000);
`
