### ISSUE TITLE
Turns off by itself

### ISSUE THREAD

**Issue by gaetankl** [j-a-n/lovelace-wallpanel#204]
Good morning ,

I have a problem since the last update, wallpanel is still activated fine, but a second later it returns to the dashboard automatically.
I couldn't find anything on the web that explains this problem.
Do you know where this problem comes from? It worked fine before the update.

Thank you for your help :)

**Comment by j-a-n** [comment]
Hello!

Could you please post your wallpanel config?

**Comment by gaetankl** [comment]
Hi ,

I followed the resolution of issue #201:
https://github.com/j-a-n/lovelace-wallpanel/issues/201

This works, you have to add /0 after the address of the wallpanel shutdown page.

screensaver_stop_navigation_path: /test-table/
VS
screensaver_stop_navigation_path: /test-table/0

The problem is solved for me. ;)

**Comment by laurenslo** [comment]
Same

**Comment by gaetankl** [comment]
When the post is resolved, should we close the post?

**Comment by j-a-n** [comment]
Please leave it open for now, I will work on a fix as soon I find the time.

**Comment by gaetankl** [comment]
> Veuillez laisser ouvert pour le moment, je travaillerai sur un correctif dès que j'aurai le temps.

Ok good :)

**Comment by j-a-n** [comment]
This should be fixed with version 4.24.1
