### ISSUE TITLE
Translation feature request

### ISSUE THREAD

**Issue by mellowism** [j-a-n/lovelace-wallpanel#21]
Hi, 
I can see my other cards translate fine, like weather and time. I would love to see this happen automatically like the other cards as well with this awesome screensaver.

**Comment by j-a-n** [comment]
Hello!
What is the problem with the translation?
Could you please try to explain it better?
A screenshot might help to understand the problem.

**Comment by mellowism** [comment]
As an example: this is my weather widget: 
![image](https://user-images.githubusercontent.com/18271469/187491130-04aa6b98-3699-4347-9425-91c2c90f923e.png)
On the same user, with the same dashboard, this is the screensaver: 
![image](https://user-images.githubusercontent.com/18271469/187491564-f38464aa-2b6d-4b87-b58a-1f051066611f.png)
How do I translate this? I've seen the other post where you can change all the strings in weather, but the other card does this automatically. Is there a way to do this with this screensaver? Or can I help with translating?

**Comment by j-a-n** [comment]
It seems that you are using the wrong addon.
The screenshot looks like a fork called "Lovelace Wallpanel Screensaver".
Please install "WallPanel" from HACS.

**Comment by mellowism** [comment]
Yea... I have no idea how I ended up with the wrong repository... More noob than I though... Sorry, I will close this.
