### ISSUE TITLE
Media-source with NFS Stockage

### ISSUE THREAD

**Issue by samidcs** [j-a-n/lovelace-wallpanel#219]
Good morning,
I used the media-source procedure to view my photos which are stored on media in a media-photos folder.
But it doesn't work
image_url: media-source://media_source/local/media_photos
I created a network storage under HA with NFS.
Thanks for your help

**Comment by samidcs** [comment]
finally i reboot and it works perfectly
sorry..

**Comment by j-a-n** [comment]
No problem, glad it works!
