### ISSUE TITLE
Stop screensaver when dashboard is no longer selected

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#22]
I use the HomeAssistant App on the iPad / iPhone.
When I select a Dashboard and the screensaver kicks in, the screensaver remains active, even when I leave the dashboard and go into any other screen within in app (file editor, has, settings, whatever)
It’s quite annoying as it always kicks in after the wartime , even while I am editing an automation. I always have to pitch on the screen to see the normal view again and after the wait time the screensaver comes back.
To avoid this, I first have to select another dashboard without Wallpanel screensaver and then go to settings etc.
Is there any way, that the screensaver stops automatically once you leave the dashboard view?

**Comment by j-a-n** [comment]
Thanks for the hint.
Issue is fixed in version v2.6.

**Comment by kwithus** [comment]
Perfect, thanks
