### ISSUE TITLE
Enhancement request - wallpanel-screensaver-image-info background

### ISSUE THREAD

**Issue by luluping** [j-a-n/lovelace-wallpanel#222]
Hi, 
first of all thanks a lot for the excellent HA component!

I've converted my old solution now to wallpanel and there is one small detail I wish to have some more flexibility.

When running wallpanel I have setup also to receive exif information for the pictures shown on the monitor. What I'm missing is an option to dynamically apply a background to the shown location data (exif information). I can define it in absolute values but then I have a box that sometimes fits well to the text and sometimes it's simply far too big since the text is only a date with the country name.

Currently I use the following config (without background, bottom, right attributes) as workaround: 
```  image_info_template: >-
    <span style="font-size: 1em; color: white; font-family: 'Roboto Noto',
    sans-serif;">
      ${DateTimeOriginal!options=day:2-digit!suffix=.}
      ${DateTimeOriginal!options=month:long}
      ${DateTimeOriginal!options=year:numeric}<br>${address.road!suffix=}
      ${address.house_number!suffix=}<br>${address.town|address.city!suffix=,}
      ${address.country}</span>
  style:
    wallpanel-screensaver-image-info:
      position: relative
      left: 15px
      top: 15px
      background: ''
      backdrop-filter: ''
```
Is there any chance to get the backgound dynamically resizes according to the text (exif data) that is related to the picture?

Thanks in advance, Sven

**Comment by j-a-n** [comment]
Hi Sven,

glad you like wallpanel!
Do you get the result you want when you add `width: fit-content` to the `wallpanel-screensaver-image-info` style?

**Comment by luluping** [comment]
Hi j-a-n, 
woooow, yes thats exactly what I was searching for!! Thanks for your fast response. Br Sven

**Comment by j-a-n** [comment]
👍
