### ISSUE TITLE
Stop screensaver when dashboard is edited

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#23]
Is there a way to stop the screensaver automatically when I edit the dashboard? 
it’s pretty hard to edit while the screensaver kicks in permanently;-)
Thanks

**Comment by j-a-n** [comment]
Yeah, that sucks.
Fixed in v3.0.

**Comment by kwithus** [comment]
Thanks!
You are really fast in fixing things!

Von meinem iPad gesendet
