### ISSUE TITLE
show_image_info issue: imageInfoCache url mismatch

### ISSUE THREAD

**Issue by dankfred** [j-a-n/lovelace-wallpanel#231]
For unsplash images, the url stored in imageInfoCache has not been passed through updateImageFromUrl.
This causes the info cache to miss in setImageDataInfo for images, as the cache url still has ${width}, ${height}, instead of the replaced values.

For whatever reason, hacs won't update the file it delivers to the browser, so I'm unable to test & submit a pr :/ 

Thanks!

**Comment by j-a-n** [comment]
Thanks for reporting!
This is fixed in version 4.25.1
