### ISSUE TITLE
Wallpanel won't start in home assistant

### ISSUE THREAD

**Issue by mfranchini** [j-a-n/lovelace-wallpanel#236]
Hello,
I have installed Wallpanel with Hacs and i added configuration like in example but screensaver won't start, nothing happen, the screen not change.
Can anyone help me?
This is my configuration

wallpanel:
  enabled: true
  debug: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  image_url: 'media-source://media/slideshow'
  idle_time: 10
  black_screen_after_time: 20

Thanks.

**Comment by j-a-n** [comment]
Hello,

where did you add this configuration?

**Comment by mfranchini** [comment]
Hello,
Added into Lovelace yaml, but with Safari on Mac it’s work, with chromium
in kiosk mode o fullscreen on raspberry pi, not work



Il giorno lun 17 giu 2024 alle 21:45 Jan Schneider ***@***.***>
ha scritto:

**Comment by j-a-n** [comment]
Please open the dev console (F12) in Chromium and look for error messages.

**Comment by mfranchini** [comment]
Ok,
if i press F12, screen saver work, then if press fF12 again not work

Marco Franchini
3487555030

**Comment by mfranchini** [comment]
There are some error 



Marco Franchini
3487555030

**Comment by mfranchini** [comment]
Hi Jan
have you see my browser error?
There is a solution?

Thanks

**Comment by j-a-n** [comment]
No, which error?

**Comment by mfranchini** [comment]
![IMG_1550](https://github.com/j-a-n/lovelace-wallpanel/assets/26694752/d7488d4b-378f-4515-b22f-8950fdfa9627)

**Comment by j-a-n** [comment]
Seems, that the Media source `media-source://media/slideshow` is not available. Please try if  HA media browser can access the source.

**Comment by mfranchini** [comment]
No, it's a mistake, media-source is solved i put a wrong dirrectory.
Wallpanel won't start, but if i press F12 Start!!!

**Comment by j-a-n** [comment]
F12 should open the browser dev console. No idea how this is related.

**Comment by mfranchini** [comment]
There isn't a solution?

**Comment by j-a-n** [comment]
Seems to be an browser issue. You can try an other browser.

**Comment by mfranchini** [comment]
with firefox same, not start

**Comment by mfranchini** [comment]
I think the problem is that wallpaper not start in kiosk o fullscreen mode, in normal windows works

**Comment by mfranchini** [comment]
Solved!!!!!!
