### ISSUE TITLE
New Unsplash API issue

### ISSUE THREAD

**Issue by mxplante** [j-a-n/lovelace-wallpanel#237]
When using the new Unplash API, background isn't working.
According to the documentation it should be as follow:
 https://api.unsplash.com/photos/random?client_id=<token>&query=<whateverquery>

However this query returns a json from which you should use a the url property ex:
` "urls": {
        "raw": "https://images.unsplash.com/photo-1600606585687-c15e3de5725f?ixid=<someid>&ixlib=rb-4.0.3",
        "full": "https://images.unsplash.com/photo-1600606585687-c15e3de5725f?crop=entropy&cs=srgb&fm=jpg&ixid=<someid>&ixlib=rb-4.0.3&q=85",
        "regular": "https://images.unsplash.com/photo-1600606585687-c15e3de5725f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=<someid>&ixlib=rb-4.0.3&q=80&w=1080",
        "small": "https://images.unsplash.com/photo-1600606585687-c15e3de5725f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=<someid>&ixlib=rb-4.0.3&q=80&w=400",
        "thumb": "https://images.unsplash.com/photo-1600606585687-c15e3de5725f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=<someid>&ixlib=rb-4.0.3&q=80&w=200",
        "small_s3": "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1600606585687-c15e3de5725f"
    },`

when running the addon, the network traces keeps pinging non-stop the following example url:
wallpanel.js?hacstag=3095064164252:304  Failed to load image: https://source.unsplash.com/random/2552x1436?sig=1718721925

using the latest version 4.25.2

**Comment by j-a-n** [comment]
I cannot reproduce this issue.
Wallpanel is using the `urls.raw` value from the API response.
Are there any errors or warnings in the browser console?

**Comment by mxplante** [comment]
Yes the was:
when running the addon, the network traces keeps pinging non-stop the following example url:
wallpanel.js?hacstag=3095064164252:304 Failed to load image: https://source.unsplash.com/random/2552x1436?sig=1718721925

**Comment by ADetDev** [comment]
Have the same issue, is there a workaround?

**Comment by j-a-n** [comment]
Does the problem still exist?
If so, please post the complete wallpanel configuration.

**Comment by DPattee** [comment]
Issue still exists. URL returns json with picture info in it, but not the picture directly. Fails to load as a background for wall panel

`wallpanel:
  enabled: true
  hide_sidebar: false
  hide_toolbar: false
  fullscreen: false
  idle_time: 10
  display_time: 60
  info_move_pattern: random
  info_move_interval: 30
  info_move_fade_duration: 1
  image_order: random
  image_list_update_interval: 3600
  image_url: >-
    https://api.unsplash.com/photos/random?client_id=[[myaccesskey]]&query=outerspace&orientation=landscape&count=1
  show_image_info: true
  image_info_template: <span style="color:#990000">//</span> ${description|alt_description}
  cards:
    - type: vertical-stack
      cards:
        - type: custom:horizon-card
          refresh_period: 300`

**Comment by j-a-n** [comment]
Wallpanel is using the urls.raw value from the API response.

**Comment by DPattee** [comment]
Just came back to update that I saw 3 images over the past 2 hours with no changes to the config I posted above. Mostly black, no image loaded.
