### ISSUE TITLE
Saving Dashboard adds ">-" after image_url: 

### ISSUE THREAD

**Issue by Dion-HA** [j-a-n/lovelace-wallpanel#239]
Hi,

It looks like there is an issue when saving the the Dashboard edits after adding the Extended eample code, the following line:

**image_url: 'http://picsum.photos/${width}/${height}?random=${timestamp}'**

is saved as:

**image_url: >-
  http://picsum.photos/${width}/${height}?random=${timestamp}**

This issue also happends on the following line copied from the Extended eample:

**text-shadow: '-2px -2px 0 #03a9f4, 2px -2px 0 #03a9f4, -2px 2px 0 #03a9f4, 2px 2px 0 #03a9f4'**

this line is saved as:

**text-shadow: >-
-2px -2px 0 #03a9f4, 2px -2px 0 #03a9f4, -2px 2px 0 #03a9f4, 2px 2px 0 
#03a9f4**

Hope you can help resolve this issue :)

Cheers!

**Comment by j-a-n** [comment]
Hi,
Home Assistant breaks long lines in the yaml configuration into several lines. Folded blocks are used for this. See https://redocly.com/docs/yaml/blocks-and-flows. This should not actually cause any problems.

**Comment by Dion-HA** [comment]
Thanks Jan, good to know. It was not updating changes I was making, then realized I had to reload YAML configuration files for changes to take effect, e.g. reloading " Groups, Group Entities, and notify Services" via the Developer tools did the trick. 

I'm now stuck on trying to remove the weather.home error, can you please let me know how to disable this weather.home entity?

Thank you,

Dion

**Comment by j-a-n** [comment]
You can remove all cards like that:
```yaml
wallpanel:
  cards: []
```
https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#badges-and-cards
