### ISSUE TITLE
unsplash.com image support

### ISSUE THREAD

**Issue by labaland** [j-a-n/lovelace-wallpanel#24]
Is it possible to use with wallpanel? 
Or add in the future?

**Comment by j-a-n** [comment]
Should work.
See https://awik.io/generate-random-images-unsplash-without-using-api/
You can try the following configuration:
```yaml
wallpanel:
  image_url: 'https://source.unsplash.com/random/${width}x${height}?fruit,night&random=${timestamp}'
```

**Comment by j-a-n** [comment]
Added an example to the README:
https://github.com/j-a-n/lovelace-wallpanel#image_url

**Comment by labaland** [comment]
> Added an example to the README: https://github.com/j-a-n/lovelace-wallpanel#image_url

It works but it only showing the same picture all the time, crossfade_time works but still the same image.
And what is the ${timestamp} at the end of the url doing? 

This is my yaml, do you see anything worng? 

wallpanel:
  enabled: true
  debug: false
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 5
  display_time: 5.0
  image_order: random
  screensaver_stop_navigation_path: /tablet-20/tablet2
  image_url: https://source.unsplash.com/random/$1920$10180?perch,beer,fishing,horse&sig=1

**Comment by j-a-n** [comment]
If the URL doesn't change, your browser will show a cache image. By adding the current timestamp, the URL will change every time.
So please try the following image_url:
```
https://source.unsplash.com/random/1920x1080?perch,beer,fishing,horse&sig=${timestamp}
```

**Comment by labaland** [comment]
Works! Thank u again :)
