### ISSUE TITLE
image_info_template: Allow templates instead of plain html

### ISSUE THREAD

**Issue by sergon2000** [j-a-n/lovelace-wallpanel#240]
Hi,

${DateTimeOriginal!options=year:numeric} to show the year works perfectly fine as long there is a DateTimeOriginal defined for that photo, but some of my old photos do not have that exif field so what it shows is 'Undefined Date'.

In those cases I'd prefer not to show anything. I'm trying to figure out how I can show the date conditionally, so that it does not show anything in case DateTimeOriginal is undefined. My first thought was by using a template but it doesn't seem to work since it only accepts plain html.
Any idea?

Thanks in advance and congrats for your work.

**Comment by j-a-n** [comment]
Hello,

if the tag value is empty, the tag should actually be omitted completely.
Could you provide an example photo?

**Comment by sergon2000** [comment]
The following code:
`<ha-icon icon="mdi:calendar"></ha-icon>
${DateTimeOriginal!options=day:numeric} de ${DateTimeOriginal!options=month:long} de ${DateTimeOriginal!options=year:numeric}`

Renders:
![Screenshot 2024-06-28 at 12 44 34](https://github.com/j-a-n/lovelace-wallpanel/assets/4072199/19804483-c473-4702-9496-f46ead6c8fde)

**Comment by j-a-n** [comment]
I would need an example photo with this kind of exif tag.

**Comment by j-a-n** [comment]
Thanks for the example photo!
Please test whether v4.25.4 fixes the problem.

**Comment by sergon2000** [comment]
It is working now, closing this issue.
Thank you!
