### ISSUE TITLE
can't seem to enable?

### ISSUE THREAD

**Issue by hs6666** [j-a-n/lovelace-wallpanel#241]
Hi, I've added the following to my dashboard (called asustab) using the raw configuration editor...

wallpanel:
  enabled: false   #  tried false and true here
  enabled_on_tabs:
    - asustab
  debug: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true

But the dashboard continues to show with the toolbar and sidebar showing

Any ideas please?

thanks

**Comment by j-a-n** [comment]
Please have a look at the FAQ:
https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#dashboard-cannot-be-edited

**Comment by j-a-n** [comment]
You can use the screensaver entity to start and stop the screensaver.
Please see https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#screensaver_entity for details.
You can use the entity in an automation, but you will need an external sensor.
Using the tablet sensors via the browser is not easy and sometimes not even technically possible.
