### ISSUE TITLE
Screen saver not starting

### ISSUE THREAD

**Issue by clintferns2911** [j-a-n/lovelace-wallpanel#245]
Hey guys

very new to github and codding, however i managed to set up the wall panel and it worked for a while
suddenly however if i click on the start screen saver entity that I've set up to start the screen saver, nothing happens.

I suspected that it's cause I'm on the beta channel for home assistant, however even after rolling back to stable, it doesn't help.

I've cleared cache still no joy.

Any idea please?

Thanks

Clinton.

**Comment by BobMac57** [comment]
2024.7 is affecting Wallpanel for some reason...

**Comment by j-a-n** [comment]
This is fixed with v4.25.3.
