### ISSUE TITLE
Uncaught error from Edge 126.0.0.0 on Windows 10 TypeError: wallpanel.screensaverRunning is not a function

### ISSUE THREAD

**Issue by danielbrunt57** [j-a-n/lovelace-wallpanel#256]
lovelace-wallpanel v4.25.4
I am noticing two back to back errors in HA 2024.7.2 after accessing Home Assistant UI via Edge browser on Windows 11:
```
2024-07-18 16:14:28.655 ERROR (MainThread) [frontend.js.latest.202407100] Uncaught error from Edge 126.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2426:16)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2464:2)
```
```2024-07-18 16:14:28.782 ERROR (MainThread) [frontend.js.latest.202407100] Uncaught error from Edge 126.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'lovelace')
new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:672:39)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2462:23)
```

**Comment by leen67** [comment]
Similar error here, from Firefox on Windows 11:
2024-07-19 13:12:37.677 ERROR (MainThread) [frontend.js.latest.202407100] Uncaught error from Firefox 128.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2426:16)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2464:2)
2024-07-19 13:12:37.758 ERROR (MainThread) [frontend.js.latest.202407100] Uncaught error from Firefox 128.0 on Windows 10
TypeError: getHaPanelLovelace() is null
WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:672:19)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2462:23)

**Comment by j-a-n** [comment]
Please try if v4.25.5 fixes the issue.

**Comment by danielbrunt57** [comment]
It did not fix it...

![image](https://github.com/user-attachments/assets/3b0b056e-d9eb-4620-8fc8-c3948cbe5f51)

```
Logger: frontend.js.latest.202407100
Source: components/system_log/__init__.py:333
First occurred: 5:38:47 PM (2 occurrences)
Last logged: 5:38:47 PM

Uncaught error from Edge 126.0.0.0 on Windows 10 TypeError: wallpanel.screensaverRunning is not a function locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2426:16) startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2464:2)
Uncaught error from Edge 126.0.0.0 on Windows 10 TypeError: Cannot read properties of null (reading 'lovelace') new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:672:39) k (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2462:23)
```

**Comment by danielbrunt57** [comment]
Ah, my bad!
Too many things on the go here.

![image](https://github.com/user-attachments/assets/406055af-8fca-488f-9edd-007dba70aed2)

```
Logger: frontend.js.latest.202407100
Source: components/system_log/__init__.py:333
First occurred: 9:26:32 PM (6 occurrences)
Last logged: 9:29:29 PM

Uncaught error from Edge 126.0.0.0 on Windows 10 TypeError: wallpanel.screensaverRunning is not a function locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2426:16) startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2464:2)
Uncaught error from Edge 126.0.0.0 on Windows 10 TypeError: Cannot read properties of null (reading 'lovelace') new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:672:39) k (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2462:23)
```

**Comment by johntdyer** [comment]
Same error on Android as welll


```
2024-07-25 13:16:09.868 ERROR (MainThread) [frontend.js.latest.202407100] Uncaught error from Firefox 128.0 on Mac OS 10.15
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2426:16)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2464:2)
2024-07-25 13:16:10.409 ERROR (MainThread) [frontend.js.latest.202407100] Uncaught error from Firefox 128.0 on Mac OS 10.15
TypeError: getHaPanelLovelace() is null
WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:672:19)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2462:23)


```

**Comment by Roger4R** [comment]
Hello, 
Yesterday I updated HA and the following error is occurring:

wallpanel.js:1193 Uncaught TypeError: this.createCardElement is not a function
    at wallpanel.js:1193:30
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js:1180:17)
    at WallpanelView.startScreensaver (wallpanel.js:2003:8)
    at WallpanelView.timer (wallpanel.js:817:10)
    
    I'm using WallPanel release v.4.25.5 - HA core v 2024.7.3 - supervisor v 2024.06.2

**Comment by Roger4R** [comment]
Screen save stopped working

**Comment by samueldowd** [comment]
`Uncaught error from WebKit 605.1.15 on iOS 17.5.1 TypeError: wallpanel.screensaverRunning is not a function. (In 'wallpanel.screensaverRunning()', 'wallpanel.screensaverRunning' is undefined) locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2427:34) /hacsfiles/lovelace-wallpanel/wallpanel.js:2467:18 dispatchEvent ([native code]::) event (src/common/dom/fire_event.ts:76:21) mainWindow.history.replaceState (src/common/navigate.ts:44:12) isNavigationClick (src/entrypoints/custom-panel.ts:132:15) `

Version 4.25.5

I haven’t been able to figure out exactly what it triggering the error. I’ve had 183 occurrences in the last 9 hours. It seems to be at least whenever I render any Lovelace page. It is definitely not limited to when I view the dashboard with Wallpanel enabled. I also tried disabling Wallpanel on the one dashboard I have it enabled on and that has not stopped the errors either.

**Comment by tOsaer** [comment]
I'm on version 4.25.6 and I still have this issue.

`2024-08-12 10:06:10.144 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 126.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29)
2024-08-12 10:06:11.239 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 126.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading '__lovelace')
new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:673:39)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2472:23)
2024-08-12 10:06:14.592 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 126.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29)
/hacsfiles/lovelace-wallpanel/wallpanel.js:2476:3
dispatchEvent (src/common/dom/fire_event.ts:76:7)
mainWindow.history.replaceState (src/common/navigate.ts:46:12)
isNavigationClick (src/layouts/home-assistant.ts:136:17)
2024-08-12 10:06:14.593 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 126.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29)
/hacsfiles/lovelace-wallpanel/wallpanel.js:2476:3
dispatchEvent (src/common/dom/fire_event.ts:76:7)
mainWindow.history.replaceState (src/common/navigate.ts:46:12)
this.updatePageEl (src/layouts/hass-router-page.ts:100:15)
update (src/reactive-element.ts:1329:13)
performUpdate (src/reactive-element.ts:1261:16)
scheduleUpdate (src/reactive-element.ts:1233:24)`

**Comment by lexiismadd** [comment]
seeing alot of these errors on my system too

**Comment by SimonWellsAus** [comment]
Same errors here...

2024-08-16 02:57:56.037 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'shadowRoot')
getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23)
SidebarCard.updateSidebarSize (/hacsfiles/sidebar-card/sidebar-card.js:18050:30)
/hacsfiles/sidebar-card/sidebar-card.js:18093:22
2024-08-16 02:57:56.038 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'shadowRoot')
getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23)
createCSS (/hacsfiles/sidebar-card/sidebar-card.js:18418:26)
updateStyling (/hacsfiles/sidebar-card/sidebar-card.js:18692:66)
/hacsfiles/sidebar-card/sidebar-card.js:18731:9
setSidebarHidden (/hacsfiles/lovelace-wallpanel/wallpanel.js:525:10)
deactivateWallpanel (/hacsfiles/lovelace-wallpanel/wallpanel.js:2415:2)
reconfigure (/hacsfiles/lovelace-wallpanel/wallpanel.js:2430:3)
/hacsfiles/lovelace-wallpanel/wallpanel.js:2496:6
2024-08-16 02:58:18.219 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading '__lovelace')
new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:673:39)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2472:23)
2024-08-16 02:58:18.837 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29)
2024-08-16 03:03:10.048 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'shadowRoot')
getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23)
SidebarCard.updateSidebarSize (/hacsfiles/sidebar-card/sidebar-card.js:18050:30)
/hacsfiles/sidebar-card/sidebar-card.js:18093:22
2024-08-16 03:03:10.048 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'shadowRoot')
getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23)
SidebarCard.updateSidebarSize (/hacsfiles/sidebar-card/sidebar-card.js:18050:30)
/hacsfiles/sidebar-card/sidebar-card.js:18093:22
2024-08-16 03:03:12.758 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading '__lovelace')
new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:673:39)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2472:23)
2024-08-16 03:03:14.450 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29)

**Comment by j-a-n** [comment]
Please test if version 4.25.7 fixes the problem.

**Comment by SimonWellsAus** [comment]
Updated errors are as follows:

2024-08-16 18:48:28.139 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading '__lovelace')
new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:673:39)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2472:23)
2024-08-16 18:48:28.740 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29)

**Comment by j-a-n** [comment]
These errors are not from version v4.25.7.
Please clear the cache of your browser.

**Comment by SimonWellsAus** [comment]
The errors now seem to be in the sidebar card

2024-08-16 19:56:20.861 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'shadowRoot')
getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23)
SidebarCard.updateSidebarSize (/hacsfiles/sidebar-card/sidebar-card.js:18050:30)
/hacsfiles/sidebar-card/sidebar-card.js:18093:22
2024-08-16 19:56:20.862 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Edge 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'shadowRoot')
getHeaderHeightPx (/hacsfiles/sidebar-card/sidebar-card.js:18640:23)
SidebarCard.updateSidebarSize (/hacsfiles/sidebar-card/sidebar-card.js:18050:30)
/hacsfiles/sidebar-card/sidebar-card.js:18093:22

**Comment by j-a-n** [comment]
The problem `wallpanel.screensaverRunning is not a function` should be solved. For other problems please create new issues.
