### ISSUE TITLE
introduce to feature : fullscreen_entity

### ISSUE THREAD

**Issue by wiless** [j-a-n/lovelace-wallpanel#257]
Just like the  `screensaver_entity` allows to enable or disable screensaver through an entity, request you to introduce another attribute/option `fullscreen_entity` to return back from full-screen.

I am using the wallpanel feature to run on a waveshare touch-screen with raspberry-pi 4. Though using touch, one can switch the browser (on firefox) to full-screen, but difficult to return back. 

Thanks for the wonderful, elegant extension

**Comment by j-a-n** [comment]
Hello!
You already can use an entity in the configuration:
```yaml
wallpanel:
  fullscreen: '${entity:input_boolean.wallpanel_fullscreen}'
```
