### ISSUE TITLE
Disable screensaver from starting if video is playing

### ISSUE THREAD

**Issue by codemunkie15** [j-a-n/lovelace-wallpanel#263]
Hi

I recently started using this on a tablet and it's been awesome. One thing I'm trying to figure out is how to stop the screensaver from starting if I have a camera feed currently playing?

For more context, I use browser mod to show different camera feeds in a popup, for x amount of time, such as my front door camera when someone rings the doorbell. I am currently sending the "stop screensaver" javascript when I want to display a feed, but then the screensaver starts again due to inactivity.

Is it possible to treat a playing video as activity so the screensaver doesn't start if I am showing a camera feed?

Many thanks

**Comment by j-a-n** [comment]
Hi,
with the new version 4.29.0 I have added the configuration `disable_screensaver_on_browser_mod_popup`.
If you set it to `true`, the screensaver will be disabled when a browser mod popup becomes active. As long as the popup is active, the screensaver will not be started again.

**Comment by codemunkie15** [comment]
Thanks very much. This is a nice solution :)

I just need to make sure all my popups on my wall tablet dashboard have timeouts now!

**Comment by codemunkie15** [comment]
@j-a-n To add to this, would it be possible to add another option to only disable if the popup contains a specific card please?

`disable_screensaver_on_browser_mod_popup_containing: "webrtc-camera"`
