### ISSUE TITLE
Broken after 2024.8.0 HA update

### ISSUE THREAD

**Issue by monte-monte** [j-a-n/lovelace-wallpanel#264]
Wallpanel not starting, webconsole prints this: ``Uncaught TypeError: this.createBadgeElement is not a function [wallpanel.js:1128:31]``

**Comment by monte-monte** [comment]
HA changed badge code in recent update: https://github.com/home-assistant/frontend/commit/729a12af0cb027b87ae6ce23397877d5781537b2

Now if you have badges enabled in wallpanel, it fails to load.

Quick fix is trivial - change ``createBadgeElement`` to ``_createBadgeElement`` here:
https://github.com/j-a-n/lovelace-wallpanel/blob/dacfb81529bd7a664a7f401391e0965b7dd06cb8/wallpanel.js#L1128C31-L1128C49

Now wallpanel loads and even shows the badge, but without name and it looks wrong, obviously changes have to be made to make it look good once again.

**Comment by Boromore** [comment]
Having the same issue. Disabled the badges for the moment.

**Comment by j-a-n** [comment]
This should be fixed in v4.25.6

**Comment by monte-monte** [comment]
@j-a-n yes, it fixed, thank you!

**Comment by Boromore** [comment]
I can confirm that is fixed. Thx @j-a-n
