### ISSUE TITLE
Broken install on 2024.8.1 HA update

### ISSUE THREAD

**Issue by screech24** [j-a-n/lovelace-wallpanel#265]
Trying to install on latest HA build gives these errors in the logs.. maybe im doing something wrong but the install seems easy enough..

> Logger: homeassistant.helpers.translation
Source: helpers/translation.py:226
First occurred: 1:38:45 AM (1 occurrences)
Last logged: 1:38:45 AM

Failed to load integration for translation: Integration 'wallpanel' not found.

> Logger: homeassistant.setup
Source: setup.py:269
First occurred: 1:38:46 AM (1 occurrences)
Last logged: 1:38:46 AM

Setup failed for 'wallpanel': Integration not found.

> Logger: frontend.js.modern.202408090
Source: components/system_log/__init__.py:333
First occurred: 1:39:58 AM (1 occurrences)
Last logged: 1:39:58 AM

Uncaught error from Chrome WebView 127.0.6533.64 on Android 14 TypeError: wallpanel.screensaverRunning is not a function locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29) /hacsfiles/lovelace-wallpanel/wallpanel.js:2476:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow.history.replaceState (src/common/navigate.ts:46:12) isNavigationClick (src/layouts/home-assistant.ts:136:17)

**Comment by tOsaer** [comment]
How did you fix it?
