### ISSUE TITLE
Error while adding repository

### ISSUE THREAD

**Issue by bjkluft** [j-a-n/lovelace-wallpanel#266]
Just wanted to install this wallpanel but run into issues trying to add the custom repository:
![image](https://github.com/user-attachments/assets/08587693-ea26-4a2e-8083-8df3bab6e81e)

Running the latest version of HA on Raspberry:
Core: 2024.8.1
Supervisor: 2024.08.0
Operating System: 12.4
Frontend: 20240809.0
HACS: 1.34.0

**Comment by j-a-n** [comment]
You do not need to add the repository. It is already included in HACS.
