### ISSUE TITLE
Styling problems with new badges

### ISSUE THREAD

**Issue by monte-monte** [j-a-n/lovelace-wallpanel#267]
One more problem with new badges after update. On some screens badge text is squeezed by other widgets.
This is how the badge looks on a dashboard:
![2024-08-12_17-58](https://github.com/user-attachments/assets/f645877d-58c3-412e-9abd-e09565d08212)
And that's how it rendered on wallpanel if screen width is a little small:
![2024-08-12_17-59](https://github.com/user-attachments/assets/07692a13-1af8-43fb-b6b9-63143b43de15)
Setting ``min-width: 90px`` fixes appearance, but maybe there is better way to deal with it?
Other way I've found is to lower ``--wp-card-width`` so widgets doesn't overextend on smaller screens.

**Comment by j-a-n** [comment]
In v4.26.0 I added `min-width` to the div. I also added the ability to use `wp_style` in the badge configuration to add custom styles for individual badges.
