### ISSUE TITLE
Issues after updating to HA 8.1

### ISSUE THREAD

**Issue by nabahr** [j-a-n/lovelace-wallpanel#268]
My HA log has been filled with errors from wallpanel after updating HA.
This is what I get after a fresh restart of HA.

```
2024-08-15 12:40:20.946 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Chrome 127.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading '__lovelace')
new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:673:39)
k (src/scoped-custom-element-registry.js:388:6)
J (src/scoped-custom-element-registry.js:236:10)
startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2472:23)
2024-08-15 12:40:21.848 ERROR (MainThread) [frontend.js.modern.202408090] Uncaught error from Chrome 127.0.0.0 on Windows 10
TypeError: wallpanel.screensaverRunning is not a function
locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2436:29)
```

Then my log is filled with other errors, all relating to `TypeError: wallpanel.screensaverRunning is not a function`.

I am a new user of wallpanel and I primarily set it up to get a nice screensaver on some viewassist devices, so I can't really say for sure what is or is not working correctly since I don't have much experience in how it should work, but I don't think the screensaver is working quite right. In particular, I don't think it is turning off when it should be.

Versions:
```
Core - 2024.8.1
Supervisor - 2024.08.0
Operating System - 13.0
Frontend - 20240809.0
lovelace-wallpanel - 4.25.6
```

**Comment by j-a-n** [comment]
Please test if version 4.25.7 fixes the problem.

**Comment by nabahr** [comment]
Looks good so far.
Thank you!
