### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by swiergot** [j-a-n/lovelace-wallpanel#269]
This is yet another issue that has started occurring with HA 2024.8, this time on Lenovo Smart Display 7 (a Google Cast screen). The screensaver won't start. Here is the full error:

```
2024-08-16 19:49:15.795 ERROR (MainThread) [frontend.js.legacy.202408090] Uncaught error from Chrome 90.0.4430.225 on Android 8.1
ReferenceError: structuredClone is not defined
/hacsfiles/lovelace-wallpanel/wallpanel.js:1148:22
HTMLElement.createInfoBoxContent (/hacsfiles/lovelace-wallpanel/wallpanel.js:1146:17)
HTMLElement.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:2109:8)
HTMLElement.timer (/hacsfiles/lovelace-wallpanel/wallpanel.js:773:10)
```

I have also Google Nest Hub (2nd gen) where everything works fine.

**Comment by swiergot** [comment]
I can see that this code was actually introduced recently as a fix to another issue. Any reason for not using `JSON.parse(JSON.stringify())`?

**Comment by j-a-n** [comment]
Yeah, I think I'm going to revert that. Seems there are still some really old browsers out there.

**Comment by Pscharumbel** [comment]
Yes, please! 🙈

**Comment by j-a-n** [comment]
This has now been reversed in v4.26.0.
