### ISSUE TITLE
Dynamically suppress screensaver

### ISSUE THREAD

**Issue by steveredden** [j-a-n/lovelace-wallpanel#271]
I'd like to be able to suppress the screen saver for windows of time during the day.

I want a specific dashboard displaying for a period of time (e.g. don't idle when displaying a bus schedule).

I've tried this without success (seems to not be being picked up?):

```yaml
wallpanel:
  enabled: true
  idle_time: |
    {% if is_state('input_boolean.wallpanel_suppress_screensaver', 'on') %}
      86400
    {% else %}
      60
    {% endif %}
```

Wondering if we need new development or if there are other workarounds in the meantime.

Is there a way to 'fake' interaction so the idle_time is not hit? some automation to send a dom event or something?

**Comment by j-a-n** [comment]
Please have a look at [Dynamic configuration using entities](https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#dynamic-configuration-using-entities) and [Profiles](https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#profiles).
Please also search in the closed issues:
https://github.com/j-a-n/lovelace-wallpanel/issues?q=is%3Aissue+is%3Aclosed+profiles

**Comment by steveredden** [comment]
You’ve thought of it all!
