### ISSUE TITLE
wallpanel.screensaverRunning is not a function locationChanged

### ISSUE THREAD

**Issue by pennisiandrea** [j-a-n/lovelace-wallpanel#274]
Hi,
I am experiencing some malfunctions on my system. Sometimes (so it is not a persistent error) wallpanel seams not to work on my dashboard, both hide_toolbar and fullscreen properties are ignored and the screensaver doesn't start. In the log I can find this error:

> Logger: frontend.js.modern.202408090
> Source: components/system_log/__init__.py:333
> First occurred: August 31, 2024 at 1:00:00 PM (84 occurrences)
> Last logged: 1:37:20 AM
> 
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.screensaverRunning is not a function locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2446:29)
>
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: Cannot read properties of undefined (reading 'style') WallpanelView.updateStyle (/hacsfiles/lovelace-wallpanel/wallpanel.js:947:27) WallpanelView.startScreensaver (/hacsfiles/lovelace-wallpanel/wallpanel.js:2097:8) set hass [as hass] (/hacsfiles/lovelace-wallpanel/wallpanel.js:714:10) this (src/state/hass-base-mixin.ts:16:14) new WallpanelView (/hacsfiles/lovelace-wallpanel/wallpanel.js:678:10) k (src/scoped-custom-element-registry.js:388:6) J (src/scoped-custom-element-registry.js:236:10) startup (/hacsfiles/lovelace-wallpanel/wallpanel.js:2482:23)
>
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.screensaverRunning is not a function locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2446:29) /hacsfiles/lovelace-wallpanel/wallpanel.js:2486:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow (src/common/navigate.ts:46:12) href (src/layouts/home-assistant.ts:136:17)
>
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.screensaverRunning is not a function locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2446:29) /hacsfiles/lovelace-wallpanel/wallpanel.js:2486:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow (src/common/navigate.ts:46:12) url (src/panels/lovelace/hui-root.ts:826:15) _navigateToView (src/panels/lovelace/hui-root.ts:553:13) updated (src/reactive-element.ts:1378:9) _$AE (src/reactive-element.ts:1343:11) performUpdate (src/reactive-element.ts:1261:16) scheduleUpdate (src/reactive-element.ts:1233:24)
>
> Uncaught error from Chrome 119.0.0.0 on Android 10 ReferenceError: drawChartOncePerHour is not defined /hacsfiles/weather-chart-card/weather-chart-card.js:18226:7

I'm running v4.26, so I really have no idea how it's possible that 
`if (wallpanel && wallpanel.screensaverRunning()) `
fails... 
It should not evaluate wallpanel.screensaverRunning() if is wallpanel is null and, at the same time, it is not possible for screensaverRunning() to be missing from wallpanel if it is not null.  But I am quite new to Javascript, so probably I'm missing something, could someone help me on this?

**Comment by j-a-n** [comment]
Hello!
It looks like you are not using the latest wallpanel version.
The running version is displayed in the browser console on startup.
If you activate [debug mode](https://github.com/j-a-n/lovelace-wallpanel/?tab=readme-ov-file#debug-mode), the version is also displayed on the screen.
There may be several versions installed in parallel. Search for `wallpanel.js` and `wallpanel.js.gz` in config/www.
Please also delete the browser cache.

**Comment by pennisiandrea** [comment]
Hi j-a-n,
actually, I'm using v4.26. 

Here some screenshots:
![config_www](https://github.com/user-attachments/assets/5f15dee3-8845-442d-8b48-a83238507771)
![Capture](https://github.com/user-attachments/assets/5770fcad-2dbf-4959-b330-12a620ddd066)

Deleting the browser cache doesn't help..

**Comment by j-a-n** [comment]
Yes, you are right.
It seems to be a follow-up error, but the actual error is not visible in the log.
Please try if version 4.27.0 fixes the problem for you.

**Comment by pennisiandrea** [comment]
Thank you very much. I'll update you after some tests

**Comment by pennisiandrea** [comment]
Hi,
unfortunately the error is still there...
This is the log:

> Logger: frontend.js.modern.202408090
> Source: components/system_log/__init__.py:333
> First occurred: 19:37:26 (37 occurrences)
> Last logged: 22:05:51
> 
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.reconfigure is not a function updateConfig (/hacsfiles/lovelace-wallpanel/wallpanel.js:423:14) reconfigure (/hacsfiles/lovelace-wallpanel/wallpanel.js:2554:2) locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2588:3) /hacsfiles/lovelace-wallpanel/wallpanel.js:2605:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow (src/common/navigate.ts:46:12) href (src/layouts/home-assistant.ts:136:17)
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.screensaverRunning is not a function updateConfig (/hacsfiles/lovelace-wallpanel/wallpanel.js:425:22) reconfigure (/hacsfiles/lovelace-wallpanel/wallpanel.js:2554:2) locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2588:3) /hacsfiles/lovelace-wallpanel/wallpanel.js:2605:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow (src/common/navigate.ts:46:12) path (src/components/ha-navigation-list.ts:65:15) call (src/lit-html.ts:2018:28) dispatchEvent (mwc-list-base.ts:403:13) notifyAction (mwc-list-foundation.ts:575:19)
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.screensaverRunning is not a function updateConfig (/hacsfiles/lovelace-wallpanel/wallpanel.js:425:22) reconfigure (/hacsfiles/lovelace-wallpanel/wallpanel.js:2554:2) locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2588:3) /hacsfiles/lovelace-wallpanel/wallpanel.js:2605:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow (src/common/navigate.ts:46:12) navigate (src/entrypoints/custom-panel.ts:132:6)
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.screensaverRunning is not a function deactivateWallpanel (/hacsfiles/lovelace-wallpanel/wallpanel.js:2540:16) reconfigure (/hacsfiles/lovelace-wallpanel/wallpanel.js:2550:3) locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2588:3) /hacsfiles/lovelace-wallpanel/wallpanel.js:2605:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow (src/common/navigate.ts:46:12) href (src/layouts/home-assistant.ts:136:17)
> Uncaught error from Chrome 119.0.0.0 on Android 10 TypeError: wallpanel.screensaverRunning is not a function updateConfig (/hacsfiles/lovelace-wallpanel/wallpanel.js:425:22) reconfigure (/hacsfiles/lovelace-wallpanel/wallpanel.js:2554:2) locationChanged (/hacsfiles/lovelace-wallpanel/wallpanel.js:2588:3) /hacsfiles/lovelace-wallpanel/wallpanel.js:2605:3 dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow (src/common/navigate.ts:46:12) a.value (src/layouts/hass-router-page.ts:100:15) update (src/reactive-element.ts:1329:13) performUpdate (src/reactive-element.ts:1261:16) scheduleUpdate (src/reactive-element.ts:1233:24)

Seams like the error has moved to other functions but I think the cause is probably the same... In the next days I will try to change browser, I'm starting to have doubts on it.
Thanks for your help.

**Comment by pennisiandrea** [comment]
After I've changed the browser the error disappears so I think the error was related somehow to the browser.
