### ISSUE TITLE
Problem with Popup from Browser Mod

### ISSUE THREAD

**Issue by Smart86** [j-a-n/lovelace-wallpanel#279]
Hello everyone,

I have a problem with the browser mod and wallpanel. I use an active screensaver in wallpanel and have the value card_interaction set to true. This works fine so far, if the z_index is set to the value 5 and the popup opens. I have 4 buttons on the popup, but then I always have to press twice for the click to be accepted. The first click ends the screen saver and after the second click the selection is made. It seems that the elements in the popup can only be selected when the screen saver has ended.

The problem exists not only with buttons, but also with all elements placed in the popup, e.g. also with entities.

Does anyone have any ideas?

**Comment by j-a-n** [comment]
Hi,
please try if the new version 4.29.0 fixes this problem.

**Comment by Smart86** [comment]
Yes, the new version solved the problem. You are great! Thank you very much!
