### ISSUE TITLE
Load images over https

### ISSUE THREAD

**Issue by robsonke** [j-a-n/lovelace-wallpanel#28]
Can we change the image url to serve over https:
https://github.com/j-a-n/lovelace-wallpanel/blob/main/wallpanel.js#L127

This line:
`
image_url: "http://picsum.photos/${width}/${height}?random=${timestamp}",
`
	
To avoid "mixed content" warnings in your browser.

**Comment by j-a-n** [comment]
Thanks for the hint!
The default value is changed in version 3.1.

**Comment by robsonke** [comment]
Thanks for the quick action :)
