### ISSUE TITLE
Adress Data is not fetched anymore

### ISSUE THREAD

**Issue by MystifHA** [j-a-n/lovelace-wallpanel#282]
It seems that the address Data of the pictures is no longer fetched from the exif information.
City / Town Information from exif isnt shown when fetch-option is disabled.

For a while everything worked fine but now this dosnt work anymore. Date and Time information from exif on the other hand is shown correctly.
Hope you can help.

**Comment by j-a-n** [comment]
Hello!
please post your wallpanel configuration so I can try to reproduce the problem.

**Comment by MystifHA** [comment]
Hello Jan,
I dont know what happened, but two hours later everthing worked again without making any changes. I cant reproduce the issue by myself. Think we can close this topic so i do now.
I'm so sorry.
