### ISSUE TITLE
Dynamic Configuration

### ISSUE THREAD

**Issue by Jon-Kraynak** [j-a-n/lovelace-wallpanel#284]
I am trying to dynamically change the enabled: (true/false) by creating an input_text.wallpanel_state helper and through automations I confirmed the state to change to true and false but enabling/disabling option for wallpanel isn't responding. Is this functionality possible? Below is how I have it configured from the documentation. Thanks for the help!

wallpanel:
  layout:
    grid-template-columns: 1375px
    grid-template-rows: 1000px
    grid-template-areas: |
      "1"
      "1"
  enabled: '${entity:input_text.wallpanel_state}'

**Comment by j-a-n** [comment]
Hello!
Since the input_text helper contains text values and `enabled` requires a boolean value, this fails.
Please try wallpanel version 4.29.1, which converts the value automatically.
