### ISSUE TITLE
Configuration doesn't kick in

### ISSUE THREAD

**Issue by cfsorensen** [j-a-n/lovelace-wallpanel#286]
Hi,

This might very well not be an issue related to the wallpanel, but maybe it's an issue with yours truly ;) Nevertheless, I hope someone with supperior knowledge can assist here.

When I try to change the configuration in wallpanel.js and save the change from Home Assistant, then the changes doesn't seem to work, when I check the code using developer tool.

![image](https://github.com/user-attachments/assets/4525f70f-ff7c-43f0-80e2-480d61de95c0)

![image](https://github.com/user-attachments/assets/1601f6ec-69f1-4b94-823e-ad868bcc7809)

Can anyone suggest how this can be fixed?

Best,
Christian

**Comment by j-a-n** [comment]
Hi Christian,
why are you trying to change the configuration in the sourcecode and not in the dashboard config?

**Comment by codemunkie15** [comment]
You need to delete the `wallpanel.js.gz` file. It's a compressed version of the source code that the browser is using. If you delete it, the browser will use your modified js file instead.
