### ISSUE TITLE
How to access or save ${image.relativePath} to use the image somewhere else

### ISSUE THREAD

**Issue by simbalasim** [j-a-n/lovelace-wallpanel#294]
Hi, thanks for this great software!

Is it somehow possible not just to show the actual unsplash-image-url but save it in an entity? Or how can I access the ${image.relativePath}? It would be really cool, to feed a generic camera entity with the image url to use the image in different places.

Or is there a cached version of the unsplash image, that can be accessed?

Or an option to download the images would also be nice possibility.

Thanks in advance!

**Comment by j-a-n** [comment]
Hi!
I'm glad you like wallpanel!
It would be possible to write the URL of the current image to an entity.
But I'm not sure how this can be used to feed a camera stream.

**Comment by AlKo77** [comment]
Hi I would also love this feature.
I am showing images from my local media store and need the path or URL of the current image shown to trigger other automations. Saving the URL in an entity would be a good solution.

**Comment by j-a-n** [comment]
Please have a look at the new [image_url_entity](https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#image_url_entity) functionality in version 4.33.0

**Comment by AlKo77** [comment]
> Please have a look at the new [image_url_entity](https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#image_url_entity) functionality in version 4.33.0

Thank you very much 👍

**Comment by simbalasim** [comment]
Don´t know how I missed all the responses. Thank you very much for this new feature! :-) 

When local files a camera can be done via [Local File Integration]( https://www.home-assistant.io/integrations/local_file)
or when web content via [Generic Camera Integration ]( https://www.home-assistant.io/integrations/generic)
