### ISSUE TITLE
[low prio feature request] Fade-out upon stop

### ISSUE THREAD

**Issue by shaiger** [j-a-n/lovelace-wallpanel#295]
The Fade-in effect is very neat. It would be great to have an exit that is just as smooth.

**Comment by j-a-n** [comment]
There is no screensaver fade-out animation yet because I thought it would probably be annoying.
After all, you stop the screensaver to be able to use the dashboard afterwards.
Or what do you think?

**Comment by shaiger** [comment]
I was thinking about the exact same tradeoff prior to submitting the FR.
The termination experience always feels a bit rough. I really like how some of the smart displays, elegantly prepare the UX for use as the user approaches, turns on lights, etc. 

It's a matter of taste of course, but here is a proposal for a more basic level of control:
**User clicks the screen:** no animation, the screensaver should vanish as quickly as possible
**Toggle helper entity switches to off** (e.g. motion/face/light have been detected): configurable animation (and duration).
A more advanced proposal:
**User clicks the screen:** no animation, the screensaver should vanish as quickly as possible
**Helper entity switches state:** (say dropdown helper that matches a list provided at config time) animation (and duration) applied in accordance to the new state.  This can allow different behavior pending on the context: change in lighting provides a smoother transition, motion fades out yet more quickly, etc. Certain devices have proximity sensors, so the closer the user is the faster the transition can be.

The simpler option probably captures 80% of the value.

**Comment by j-a-n** [comment]
Hello @shaiger !
Thanks for your input.
This is now implemented in wallpanel 4.31.0.
Looking forward to your feedback.

**Comment by shaiger** [comment]
Love it! Even the very slight fade-out for interaction provides a very elegant touch IMHO!

I've noticed the motion fade time, and I may have a few inputs to add (which bare in mind are also extremely esoteric).
I have an overly complicated yet very enjoyable project that is aiming to mimic how many smart displays operate when engaged/disengaged. 
The cool thing about the camera delay/integration, is that it's local and simple. For my needs, I do require an HA automation for most of engagement logic logic. It would be nice if the management of engagement would all be done locally, but for advanced set ups I don't think it would be enough if TBH. A few examples:
* Different behavior for face detection (WebView apps as WallPanel and Fully support this)
* Dedicated logic upon changes in illuminance (when it is dark, I use a different screensaver profile, lower the device brightness, etc)
* I have sentence for waking up the device (turns on the screen if off, stops the screensaver, etc). Ideally I could apply this logic for every Assist interaction, but that is besides the point.
* I close pop-ups and navigate to the homepage based on lack of motion/face detection, even prior to starting the screensaver
The list goes on... 
I use some combo of the mobile app, WallPanel (the Android app), Tasker, etc to get this to work. I reached a reliable setup which is also very easy to maintain across multiple devices.
The point is that for advanced (some say overly engineered) use-cases, more granular control is required. And a counter argument is that it doesn't need to be all or nothing, the more you can do locally - the better :)
Thanks again for the super neat feature!

**Comment by shaiger** [comment]
Closing the issue as the functionality has been added and works as intended!
Thanks!
