### ISSUE TITLE
Feature: Themes for different seasons (change the image url)

### ISSUE THREAD

**Issue by kobraevents** [j-a-n/lovelace-wallpanel#301]
hey there,

thanks again for this nice project.
i try to figure out how to implement a season trigger/ themes folder for different periods of the year. should be as simple as change the image url, but wallpanel stops working (shows white border and blinking image icon on the top left).

1. Try
yaml config
template:
  - sensor:
    - name: Dynamic Wallpanel Image Selector
      unique_id: "dynamic_wallpanel_image_selector"
      state: >
          {% set month = now().month %}
          {% set day = now().day %}
          {% if month == 10 and 28 <= day <= 31 %}
            'media-source://media_source/local/pictures/Halloween'
          {% elif month == 12 and 24 <= day <= 26 %}
            'media-source://media_source/local/pictures/Winter'
          {% else %}
            'media-source://media_source/local/pictures/Home'
          {% endif %}  

place the sensor.dynamic_wallpanel_image_selector at image_url: in wallpanel config

2. Try
place the function directly in sketch at wallpanel
image_url: >
          {% set month = now().month %}
          {% set day = now().day %}
          {% if month == 10 and 28 <= day <= 31 %}
            'media-source://media_source/local/pictures/Halloween'
          {% elif month == 12 and 24 <= day <= 26 %}
            'media-source://media_source/local/pictures/Winter'
          {% else %}
            'media-source://media_source/local/pictures/Home'
          {% endif %} 

Result: blinking white borders, no images

Sensor is working fine in HA, gives the right "url" back as state. Also tryed with and without the **'** .

any ideas?

**Comment by j-a-n** [comment]
You can use an entity to dynamically set the `image_url`.
For example:
```yaml
wallpanel:
  image_url: '${entity:input_text.wallpanel_image_url}'
```
Then use an automation to set the value of the entity.

See  https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#dynamic-configuration-using-entities for details.

**Comment by kobraevents** [comment]
thanks for the fast support!

get it to work!
