### ISSUE TITLE
enabled_on_tabs does not work as expected

### ISSUE THREAD

**Issue by Adesfire** [j-a-n/lovelace-wallpanel#302]
Hi there,
I am trying to setup the last version of Wallpanel on the latest version of HA :)

Doing so, I wanted to limit this feature to only one view, called phone.
For that I use the following code:

```
wallpanel:
  enabled: true
  enabled_on_tabs:
    - Phone
  debug: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
views:
[...]
- title: Phone
    path: phone
    type: sections
    max_columns: 1
    sections:
```

However, as soon as I save my change, the browser goes fullscreen whatever the tabs I am on...
Did I do something stupid, instructions seems crystal clear though...

Any help is appreciated!

**Comment by j-a-n** [comment]
Hello!
The full screen is currently activated directly when the wallpanel becomes active.
The setting `enabled_on_tabs` has no effect on the handling of the full screen.
