### ISSUE TITLE
Hide toolbar but show space

### ISSUE THREAD

**Issue by pandaboy6621** [j-a-n/lovelace-wallpanel#305]
I'm not quite sure how to describe this situation, but when I enable the wall panel, my navigation bar is hidden, which is what I want. However, when the bar is hidden, I would like it to be replaced with a gap of the same height as the toolbar. Currently, the Lovelace cards at the top of my dashboard jump up to the top of the screen. So, I would like the option to maintain a space where the toolbar used to be.

**Comment by j-a-n** [comment]
Please see the new option `keep_toolbar_space` in the latest wallpanel release [v4.32.0](https://github.com/j-a-n/lovelace-wallpanel/releases/tag/v4.32.0).
I hope this is what you need!
