### ISSUE TITLE
4.3.1 No longer honours wp_enabled=true

### ISSUE THREAD

**Issue by ProximusAl** [j-a-n/lovelace-wallpanel#308]
I have a tablet that I launch FullyKiosk with my http://homeassistant/?wp_enabled=true

This has always hidden the sidebar and top bar. 

Since updating to 4.3.1 this no longer works. Sidebar and Toolbar is back. 

I’ve rolled back to 4.3.0 in HACS and this has resolved it.

**Comment by KennyMarcum** [comment]
Same, Just updated to 4.3.1 and I'm getting both the sidebar and toolbar.  This was working fine before the update.  Cleared fully kiosk cache and history and restarted app on tablet.  Nothing seems to make them go away.

wallpanel:
  enabled: true
  debug: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: false
  idle_time: 0

**Comment by j-a-n** [comment]
Please check if this is fixed with version 4.31.1.

**Comment by akinin** [comment]
> Please check if this is fixed with version 4.31.1.

It works, thank you!
