### ISSUE TITLE
Excess scrolling area at end of page

### ISSUE THREAD

**Issue by meks007** [j-a-n/lovelace-wallpanel#309]
Hi,

the latest release introduced a bug that leads to excess scrolling area on every lovelace dashboard (not only in wallpanel-mode) due to 

`
<video id="wallpanelMotionDetectionVideo" style="visibility: hidden;"></video>
<canvas id="wallpanelMotionDetectionCanvas"></canvas>
`

Excess scrolling area is removed when both(!) tags are removed.

**Comment by j-a-n** [comment]
Thanks for reporting.
Which browser are you using?

**Comment by meks007** [comment]
most current firefox
same behaviour on chrome tho

**Comment by j-a-n** [comment]
Please check if version 4.31.2 fixes the issue.
