### ISSUE TITLE
Integration error: wallpanel - Integration 'wallpanel' not found.

### ISSUE THREAD

**Issue by Xekz** [j-a-n/lovelace-wallpanel#31]
add from hacs

in config >>>
weather:
   platform: gismeteo

wallpanel:
  enabled: true

**Comment by j-a-n** [comment]
Where is the error message displayed?

**Comment by Xekz** [comment]
On restart homeasist or check config

**Comment by j-a-n** [comment]
Please add the wallpanel config to your dashboard config, not the configuration.yaml
