### ISSUE TITLE
Suggestion: Hide cursor option

### ISSUE THREAD

**Issue by Sinaloit** [j-a-n/lovelace-wallpanel#310]
It would be useful for wallpanels to have a hide cursor option.  While there are ways to do this with wayfire/X11  it should be possible by adding `cursor: none;` to the CSS of specific panels.  Would it be possible to add this as an option to the wallpanel mod?

**Comment by j-a-n** [comment]
Hello!
Adding `cursor: none` to specific panels would not be enough.
There are many elements / css classes that set pointer attributes (`ha-card` uses `cursor: pointer` for example).
These would have priority and would overwrite the `cursor: none` of the panel.
