### ISSUE TITLE
OPTION: Store Pictures in a puffer

### ISSUE THREAD

**Issue by kobraevents** [j-a-n/lovelace-wallpanel#311]
hey there,
wallpanel runs fine with pictures and also some gif (for animated pictures).

but i still got some trouble by different internet service provider. so if the internet speed is slow than pictures loading and gif files arent fluent. is there an option to store the next or current file in a puffer? so the wallpanel could play/show the actual pictures localy stored instead of streaming a gif or pictures from my HA-server.

greetings and peaceful christmas season.

for example and all of you a looped video created by me. please note you have to convert it into a gif for yourself.

https://github.com/user-attachments/assets/a0b79bfb-3c18-4413-b2c4-b9322f834d1a

**Comment by j-a-n** [comment]
Hello!
When the wallpanel displays an image, the next image is already preloaded in the background. Increasing the display_time can therefore help. Implementing a cache is not trivial. I don't think I will consider that in the near future.

I also wish you a happy christmas season.
