### ISSUE TITLE
The added card is cut off.

### ISSUE THREAD

**Issue by 13860605362** [j-a-n/lovelace-wallpanel#318]
![1734773353350](https://github.com/user-attachments/assets/791969e3-a59d-4146-8cd7-542d47c6fc17)
The information on the left side was originally fully filling the screen. However, after recently updating both Wallpanel and Home Assistant, I found that it is not displaying correctly anymore.

It is clear that the content at the top, left, and bottom has been cut off, and they cannot be fully displayed. It seems that the width of the cut-off areas is the same and has rounded corners.

I haven't changed the contents of the configuration file. Has anyone encountered a similar issue? What could be the possible reasons for this?

**Comment by j-a-n** [comment]
Some changes were made to the standard styles in version 4.32.0:

https://github.com/j-a-n/lovelace-wallpanel/compare/v4.31.2...v4.32.0

**Comment by 13860605362** [comment]
> 对版本 4.32.0 中的标准样式进行了一些更改：
> 
> [4.31.2 版...4.32.0 版](https://github.com/j-a-n/lovelace-wallpanel/compare/v4.31.2...v4.32.0)

Sorry, I'm a beginner, and I'm trying my best to understand it. I just want to know if I can still achieve the previous style?

**Comment by j-a-n** [comment]
Can you please post your wallpanel config?

**Comment by 13860605362** [comment]
> 您能发布您的墙板配置吗？


![1734789902304](https://github.com/user-attachments/assets/bb8a532b-e75c-453c-b56c-97065c32742d)


```
wallpanel:
  enabled: true
  enabled_on_tabs: []
  debug: false
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 15
  fade_in_time: 2
  display_time: 300
  keep_screen_on_time: 0
  black_screen_after_time: 0
  control_reactivation_time: 1
  stop_screensaver_on_mouse_move: true
  stop_screensaver_on_location_change: true
  screensaver_stop_navigation_path: /dashboard-pad/light
  image_url: media-source://media_source/local/wallpaper
  image_fit: cover
  image_list_update_interval: 600
  image_order: random
  image_excludes: []
  show_image_info: false
  fetch_address_data: false
  image_info_template: >-
    ${address.town|address.city!prefix=!suffix= //
    }${DateTimeOriginal!options=year:numeric,month:long}
  info_animation_duration_x: 0
  info_animation_duration_y: 0
  info_animation_timing_function_x: ease
  info_animation_timing_function_y: ease
  info_move_pattern: corners
  info_move_interval: 0
  info_move_fade_duration: 0
  card_interaction: true
  cards:
    - type: custom:stack-in-card
      cards:
        - type: iframe
          url: /local/ui/翻页时钟/flip_clock2.html
          aspect_ratio: 35%
          card_mod:
            style: |
              ha-card {
                background-color: rgba(255, 255, 255, 0);
              }
        - type: custom:qweather-card
          entity: weather.he_feng_tian_qi
          show_attributes: true
          show_hourly_forecast: false
          show_daily_forecast: true
          show_daily_chart: true
          show_daily_date: false
          show_condition_text: true
          show_keypoint: true
          show_warning: true
          show_warningtext: false
          show_night: false
          show_wind: false
          show_daily_temperature: false
          show_thick_border: false
          card_mod:
            style: |
              ha-card {
                background-color: rgba(255, 255, 255, 0);
              }
        - type: markdown
          card_mod:
            style: |
              ha-card {
                background-color: rgba(255, 255, 255, 0);
              }
          content: |

            ㅤ
            ㅤ
            ㅤ
            ㅤ
            ㅤ
            ㅤ
            ㅤ
            ㅤ
            ㅤ
      wp_style:
        margin-top: '-25px'
        margin-left: '-25px'
        width: 350px
        grid-row: 1
        grid-column: 1
        '--ha-card-background': rgba(10, 10, 10, 0.4)
        '--ha-card-border-radius': 0px
        backdrop-filter: blur(2px)
```


I just made a card that's a bit longer. 

wp_style: 
margin-top: '-25px' 
margin-left: '-25px'

Then I moved it up and to the left. I found an old example, haha. I know this isn’t the usual way to do it, but it really gives me the effect I wanted!

**Comment by alkusa** [comment]
> > 您能发布您的墙板配置吗?
> 
> ![1734789902304](https://private-user-images.githubusercontent.com/106414624/397932348-bb8a532b-e75c-453c-b56c-97065c32742d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MzAzMTcsIm5iZiI6MTczNTQzMDAxNywicGF0aCI6Ii8xMDY0MTQ2MjQvMzk3OTMyMzQ4LWJiOGE1MzJiLWU3NWMtNDUzYy1iNTZjLTk3MDY1YzMyNzQyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQyMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjQzNGU5ODg2YmNhMDAwODk0NDdkYjMwMzNmMGIzYWU4ZmY4YTk5NDk4Mjc4MmVlMjg2NzlkZjhjZjNhNTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zk0w2xyaB3ANT751SvdDry2ALz9mSl7yLvUS6r4p8DQ)
> 
> ```
> wallpanel:
>   enabled: true
>   enabled_on_tabs: []
>   debug: false
>   hide_toolbar: false
>   hide_sidebar: false
>   fullscreen: false
>   idle_time: 15
>   fade_in_time: 2
>   display_time: 300
>   keep_screen_on_time: 0
>   black_screen_after_time: 0
>   control_reactivation_time: 1
>   stop_screensaver_on_mouse_move: true
>   stop_screensaver_on_location_change: true
>   screensaver_stop_navigation_path: /dashboard-pad/light
>   image_url: media-source://media_source/local/wallpaper
>   image_fit: cover
>   image_list_update_interval: 600
>   image_order: random
>   image_excludes: []
>   show_image_info: false
>   fetch_address_data: false
>   image_info_template: >-
>     ${address.town|address.city!prefix=!suffix= //
>     }${DateTimeOriginal!options=year:numeric,month:long}
>   info_animation_duration_x: 0
>   info_animation_duration_y: 0
>   info_animation_timing_function_x: ease
>   info_animation_timing_function_y: ease
>   info_move_pattern: corners
>   info_move_interval: 0
>   info_move_fade_duration: 0
>   card_interaction: true
>   cards:
>     - type: custom:stack-in-card
>       cards:
>         - type: iframe
>           url: /local/ui/翻页时钟/flip_clock2.html
>           aspect_ratio: 35%
>           card_mod:
>             style: |
>               ha-card {
>                 background-color: rgba(255, 255, 255, 0);
>               }
>         - type: custom:qweather-card
>           entity: weather.he_feng_tian_qi
>           show_attributes: true
>           show_hourly_forecast: false
>           show_daily_forecast: true
>           show_daily_chart: true
>           show_daily_date: false
>           show_condition_text: true
>           show_keypoint: true
>           show_warning: true
>           show_warningtext: false
>           show_night: false
>           show_wind: false
>           show_daily_temperature: false
>           show_thick_border: false
>           card_mod:
>             style: |
>               ha-card {
>                 background-color: rgba(255, 255, 255, 0);
>               }
>         - type: markdown
>           card_mod:
>             style: |
>               ha-card {
>                 background-color: rgba(255, 255, 255, 0);
>               }
>           content: |
> 
>             ㅤ
>             ㅤ
>             ㅤ
>             ㅤ
>             ㅤ
>             ㅤ
>             ㅤ
>             ㅤ
>             ㅤ
>       wp_style:
>         margin-top: '-25px'
>         margin-left: '-25px'
>         width: 350px
>         grid-row: 1
>         grid-column: 1
>         '--ha-card-background': rgba(10, 10, 10, 0.4)
>         '--ha-card-border-radius': 0px
>         backdrop-filter: blur(2px)
> ```
> 
> Ich habe gerade eine Karte gemacht, die etwas länger ist.
> 
> wp_Stil:Rand-Top: '-25px'linker Rand: '-25px'
> 
> Dann habe ich es nach oben und nach links verschoben. Ich habe ein altes Beispiel gefunden, haha. Ich weiß, dass dies nicht die übliche Art ist, es zu tun, aber es gibt mir wirklich den Effekt, den ich wollte!

Thanks for your contribution. But can you explain to me in detail where I have to insert the additional code? I am a total beginner in YAML and don't understand your solution approach.

**Comment by 13860605362** [comment]
> > > 您能发布您的墙板配置吗?
> > 
> > 
> > ![1734789902304](https://private-user-images.githubusercontent.com/106414624/397932348-bb8a532b-e75c-453c-b56c-97065c32742d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MzAzMTcsIm5iZiI6MTczNTQzMDAxNywicGF0aCI6Ii8xMDY0MTQ2MjQvMzk3OTMyMzQ4LWJiOGE1MzJiLWU3NWMtNDUzYy1iNTZjLTk3MDY1YzMyNzQyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQyMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjQzNGU5ODg2YmNhMDAwODk0NDdkYjMwMzNmMGIzYWU4ZmY4YTk5NDk4Mjc4MmVlMjg2NzlkZjhjZjNhNTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zk0w2xyaB3ANT751SvdDry2ALz9mSl7yLvUS6r4p8DQ)
> > ```
> > wallpanel:
> >   enabled: true
> >   enabled_on_tabs: []
> >   debug: false
> >   hide_toolbar: false
> >   hide_sidebar: false
> >   fullscreen: false
> >   idle_time: 15
> >   fade_in_time: 2
> >   display_time: 300
> >   keep_screen_on_time: 0
> >   black_screen_after_time: 0
> >   control_reactivation_time: 1
> >   stop_screensaver_on_mouse_move: true
> >   stop_screensaver_on_location_change: true
> >   screensaver_stop_navigation_path: /dashboard-pad/light
> >   image_url: media-source://media_source/local/wallpaper
> >   image_fit: cover
> >   image_list_update_interval: 600
> >   image_order: random
> >   image_excludes: []
> >   show_image_info: false
> >   fetch_address_data: false
> >   image_info_template: >-
> >     ${address.town|address.city!prefix=!suffix= //
> >     }${DateTimeOriginal!options=year:numeric,month:long}
> >   info_animation_duration_x: 0
> >   info_animation_duration_y: 0
> >   info_animation_timing_function_x: ease
> >   info_animation_timing_function_y: ease
> >   info_move_pattern: corners
> >   info_move_interval: 0
> >   info_move_fade_duration: 0
> >   card_interaction: true
> >   cards:
> >     - type: custom:stack-in-card
> >       cards:
> >         - type: iframe
> >           url: /local/ui/翻页时钟/flip_clock2.html
> >           aspect_ratio: 35%
> >           card_mod:
> >             style: |
> >               ha-card {
> >                 background-color: rgba(255, 255, 255, 0);
> >               }
> >         - type: custom:qweather-card
> >           entity: weather.he_feng_tian_qi
> >           show_attributes: true
> >           show_hourly_forecast: false
> >           show_daily_forecast: true
> >           show_daily_chart: true
> >           show_daily_date: false
> >           show_condition_text: true
> >           show_keypoint: true
> >           show_warning: true
> >           show_warningtext: false
> >           show_night: false
> >           show_wind: false
> >           show_daily_temperature: false
> >           show_thick_border: false
> >           card_mod:
> >             style: |
> >               ha-card {
> >                 background-color: rgba(255, 255, 255, 0);
> >               }
> >         - type: markdown
> >           card_mod:
> >             style: |
> >               ha-card {
> >                 background-color: rgba(255, 255, 255, 0);
> >               }
> >           content: |
> > 
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >       wp_style:
> >         margin-top: '-25px'
> >         margin-left: '-25px'
> >         width: 350px
> >         grid-row: 1
> >         grid-column: 1
> >         '--ha-card-background': rgba(10, 10, 10, 0.4)
> >         '--ha-card-border-radius': 0px
> >         backdrop-filter: blur(2px)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ich habe gerade eine Karte gemacht， die etwas länger ist.
> > wp_Stil：Rand-Top： '-25px'链接器 Rand： '-25px'
> > Dann habe ich es nach oben und nach links verschoben.Ich habe ein altes Beispiel gefunden， haha.Ich weiß， dass dies nicht die übliche Art ist， es zu tun， aber es gibt mir wirklich den Effekt， den ich wollte！
> 
> 感谢您的贡献。但是您能向我详细解释一下我必须在何处插入附加代码吗？我是 YAML 的初学者，不了解你的解决方案方法。



> > > 您能发布您的墙板配置吗?
> > 
> > 
> > ![1734789902304](https://private-user-images.githubusercontent.com/106414624/397932348-bb8a532b-e75c-453c-b56c-97065c32742d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MzAzMTcsIm5iZiI6MTczNTQzMDAxNywicGF0aCI6Ii8xMDY0MTQ2MjQvMzk3OTMyMzQ4LWJiOGE1MzJiLWU3NWMtNDUzYy1iNTZjLTk3MDY1YzMyNzQyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQyMzUzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjQzNGU5ODg2YmNhMDAwODk0NDdkYjMwMzNmMGIzYWU4ZmY4YTk5NDk4Mjc4MmVlMjg2NzlkZjhjZjNhNTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zk0w2xyaB3ANT751SvdDry2ALz9mSl7yLvUS6r4p8DQ)
> > ```
> > wallpanel:
> >   enabled: true
> >   enabled_on_tabs: []
> >   debug: false
> >   hide_toolbar: false
> >   hide_sidebar: false
> >   fullscreen: false
> >   idle_time: 15
> >   fade_in_time: 2
> >   display_time: 300
> >   keep_screen_on_time: 0
> >   black_screen_after_time: 0
> >   control_reactivation_time: 1
> >   stop_screensaver_on_mouse_move: true
> >   stop_screensaver_on_location_change: true
> >   screensaver_stop_navigation_path: /dashboard-pad/light
> >   image_url: media-source://media_source/local/wallpaper
> >   image_fit: cover
> >   image_list_update_interval: 600
> >   image_order: random
> >   image_excludes: []
> >   show_image_info: false
> >   fetch_address_data: false
> >   image_info_template: >-
> >     ${address.town|address.city!prefix=!suffix= //
> >     }${DateTimeOriginal!options=year:numeric,month:long}
> >   info_animation_duration_x: 0
> >   info_animation_duration_y: 0
> >   info_animation_timing_function_x: ease
> >   info_animation_timing_function_y: ease
> >   info_move_pattern: corners
> >   info_move_interval: 0
> >   info_move_fade_duration: 0
> >   card_interaction: true
> >   cards:
> >     - type: custom:stack-in-card
> >       cards:
> >         - type: iframe
> >           url: /local/ui/翻页时钟/flip_clock2.html
> >           aspect_ratio: 35%
> >           card_mod:
> >             style: |
> >               ha-card {
> >                 background-color: rgba(255, 255, 255, 0);
> >               }
> >         - type: custom:qweather-card
> >           entity: weather.he_feng_tian_qi
> >           show_attributes: true
> >           show_hourly_forecast: false
> >           show_daily_forecast: true
> >           show_daily_chart: true
> >           show_daily_date: false
> >           show_condition_text: true
> >           show_keypoint: true
> >           show_warning: true
> >           show_warningtext: false
> >           show_night: false
> >           show_wind: false
> >           show_daily_temperature: false
> >           show_thick_border: false
> >           card_mod:
> >             style: |
> >               ha-card {
> >                 background-color: rgba(255, 255, 255, 0);
> >               }
> >         - type: markdown
> >           card_mod:
> >             style: |
> >               ha-card {
> >                 background-color: rgba(255, 255, 255, 0);
> >               }
> >           content: |
> > 
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >             ㅤ
> >       wp_style:
> >         margin-top: '-25px'
> >         margin-left: '-25px'
> >         width: 350px
> >         grid-row: 1
> >         grid-column: 1
> >         '--ha-card-background': rgba(10, 10, 10, 0.4)
> >         '--ha-card-border-radius': 0px
> >         backdrop-filter: blur(2px)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ich habe gerade eine Karte gemacht, die etwas länger ist.
> > wp_Stil:Rand-Top: '-25px'linker Rand: '-25px'
> > Dann habe ich es nach oben und nach links verschoben. Ich habe ein altes Beispiel gefunden, haha. Ich weiß, dass dies nicht die übliche Art ist, es zu tun, aber es gibt mir wirklich den Effekt, den ich wollte!
> 
> Thanks for your contribution. But can you explain to me in detail where I have to insert the additional code? I am a total beginner in YAML and don't understand your solution approach.

Please paste it at the very beginning of the dashboard code. I just added a regular card on WallPanel, and normally, cards don’t stick to the edges of the screen. But I moved it up and to the left to make it look like it fills the left side of the screen. Unfortunately, after the recent update, it’s not displaying properly anymore. Honestly, I'm just a beginner too and I have no idea how to fix it, which is why I posted the issues.

**Comment by j-a-n** [comment]
You can just remove the padding like this:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-container:
      padding: 0px
```
And remove:
```
margin-top: '-25px'
margin-left: '-25px'
```

**Comment by 13860605362** [comment]
> 你可以像这样删除填充：
> 
> ```yaml
> wallpanel:
>   style:
>     wallpanel-screensaver-info-container:
>       padding: 0px
> ```
> 
> 并删除：
> 
> ```
> margin-top: '-25px'
> margin-left: '-25px'
> ```

After making the changes you suggested, there is still a slight gap, but I found that

margin-top: '-2px'
margin-left: '-2px'

are effective. Thank you very much
