### ISSUE TITLE
Restrict exif date shown to year/month?

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#32]
The default for the exif date shown is the full info, (year-month-day-hours-minutes-seconds, which not now takes a lot of room but is also mostly just to much info 
Is there a way to limit it to year or year/month or year/month/day ?

**Comment by j-a-n** [comment]
With version 3.5 you can set format options for dates.
For example: `${DateTimeOriginal!options=year:numeric,month:short}`

**Comment by kwithus** [comment]
Thanks, perfect
