### ISSUE TITLE
Reset screensaver_entity state to off when the dashboard is loaded

### ISSUE THREAD

**Issue by j9brown** [j-a-n/lovelace-wallpanel#321]
## Situation

Assume that the `screensaver_entity` option has been configured for a given browser profile.

When the screensaver starts, it turns on the  screensaver entity.  If the browser is refreshed while the screensaver is running, then the screensaver entity remains on because the screensaver never properly exited.  That's to be expected due to the interruption.

However, after the browser reloads the dashboard, the screensaver entity remains on even though the screensaver is demonstrably not running.  This causes problems for some scripts.  For example, to start the screensaver, a script must first turn off the screensaver entity, then wait a moment for the state change to be noticed, and finally turn the screensaver entity back on again to finish triggering the screensaver.

## Proposed Solution

When wallpanel finishes loading, it can immediately turn the screensaver entity off to reflect its actual state.

## Alternative Solution

If the screensaver entity is still on when wallpanel finishes loading, then start the screensaver immediately.  This makes the race condition go away although it might be a bit harder to escape broken states such as hangs by refreshing the browser.

**Comment by j-a-n** [comment]
Hello!
You are right, the `screensaver_entity` is now updated in version 4.33.0 at startup.
