### ISSUE TITLE
screensaver_entity is missing

### ISSUE THREAD

**Issue by 503Dev** [j-a-n/lovelace-wallpanel#39]
Issue: Wallpanel works as expected however there is no entity created (checked via Dev Tools -> Entities) created named "nput_boolean.wallpanel_screensaver", as a result it is not possible to control this element.  I have tried reinstalling Wallpanel to no avail.  Any tips on this would be appreciated.

Environment: Home Assistant 2022.9.5 (latest)
Wallpanel: 4.0
BrowserMod: Latest

Resource load:
`    - url: /hacsfiles/lovelace-wallpanel/wallpanel.js?v2`
`      type: module`

Config snippet: 
`screensaver_entity: input_boolean.wallpanel_screensaver`

**Comment by j-a-n** [comment]
You will have to create that input_boolean manually in the HA helpers page.

**Comment by 503Dev** [comment]
@j-a-n Ah geez, thank you.  I am such a newb sometimes.  I am a fellow programmer and I always overthink stuff when the answer is really easy.

To anyone else stuck:

1. Open HA UI 
2. Goto Settings -> Devices & Services -> Helpers
3. Add a new helper of type **toggle**
4. Name it: wallpanel_screensaver     (default per the config examples, can be adjusted)
5. Save 

It works right away after adding it, no need to refresh or anything.

Thanks very much for your amazing work.

**Comment by j-a-n** [comment]
You're welcome!
