### ISSUE TITLE
[FR]: Redirect URL

### ISSUE THREAD

**Issue by SendNukez** [j-a-n/lovelace-wallpanel#4]
Would it be possible to make dismissing the screensaver redirect to a page?
My use would be to have it redirect me to my Lovelace "home page", as every level in our home has a different dashboard and one main page. It would be nice to be redirected to the main page when tapping.

Maybe this could be generalized by using something like Home Assistant's [dashboard actions](https://www.home-assistant.io/dashboards/actions/#tap_action).

Thank you for making this great Screensaver!

**Comment by j-a-n** [comment]
Nice suggestion, thanks!
It is now implemented in Version 2.1 of the addon.
For example you can use `screensaver_stop_navigation_path: /lovelace/default_view`.
