### ISSUE TITLE
Restrict screensaver to one or specified tabs (pages)

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#42]
For me the screensaver makes only sense for the start tab/page of my dashboard. On the other tabs it's rather contraproductive, as I look at those tabs for specific reason and don't want to be disturbed by the screensaver popping up.
So, is there a way to limit the screensaver so just one or a number of specified tabs?

**Comment by j-a-n** [comment]
In version 4.2 you can set `enabled_on_tabs`:
```yaml
  enabled_on_tabs:
    - default_view
```

**Comment by kwithus** [comment]
perfectVon meinem iPhone gesendetAm 25.09.2022 um 19:14 schrieb j-a-n ***@***.***>:﻿
In version 4.2 you can set enabled_on_tabs:
  enabled_on_tabs:
    - default_view
