### ISSUE TITLE
Restrict hide hide_toolbar/sidebar to selected tabs

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#44]
When I restrict the screensaver to specific pages (e.g. default view) and also set hide_toolbar / hide_sidebar to true the screensaver is effectively restricted to the selected tabs, however toolbar/sidebar is hidden on other tabs as well.
Only when I switch to another tab and then reload the dashboard the sidebar/toolbar on the other tab is visible.
It would be better, if the sidebar/toolbar shows up as soon as I switch to a different tab.

**Comment by j-a-n** [comment]
Yes, I agree.
Changed in version 4.3.

**Comment by kwithus** [comment]
👍 Von meinem iPhone gesendetAm 03.10.2022 um 08:42 schrieb j-a-n ***@***.***>:﻿
Yes, I agree.
Changed in version 4.3.
