### ISSUE TITLE
wallpanel on google home hub 

### ISSUE THREAD

**Issue by FinestDice17** [j-a-n/lovelace-wallpanel#45]
I cast dashboards to various google home hubs in my house but noticed that the wallpanel screensaver kicks in on any of them. Is there a way to get it to work that im over looking?

**Comment by j-a-n** [comment]
I think all devices play the same stream, so there can be no solution.

**Comment by ikolsteren** [comment]
I have started to have success linking my wallpanel card dashboard to my home hubs using this project - https://github.com/AlexxIT/DashCast
When I use DashCast to send my lovelace-wallpanel card the screen saver kicks in.   There are ways to make sure DashCast keeps the page loaded and google not taking over.   Only started with both over the past couple days but have been happy so far

**Comment by elgaspar** [comment]
@ikolsteren How did you manage to get past the login page of home assistant? Can you share your setup?

**Comment by ikolsteren** [comment]
> @ikolsteren How did you manage to get past the login page of home assistant? Can you share your setup?

I think I have mine a bit messed up at the moment - using trusted networks and trusted users is what I had.  currently just have my trusted network and select the user the first time for the dashboard 

https://www.home-assistant.io/docs/authentication/providers/
