### ISSUE TITLE
Browser recognizing current device question

### ISSUE THREAD

**Issue by kamilk91** [j-a-n/lovelace-wallpanel#46]
Hello 
you gave example, so i decided to ask about something.
```
wallpanel:
  enabled: true
  screensaver_entity: input_boolean.screensaver_firebrowser

```

i can't find this input entity in homeassistant. Is it all right ? 

![image](https://user-images.githubusercontent.com/26136300/194859846-e4c11906-8b37-48dd-9652-de9cf421551c.png)
![image](https://user-images.githubusercontent.com/26136300/194860000-0adb8f43-79ff-4156-a715-a8d3200ae058.png)

**Comment by j-a-n** [comment]
Hello,
you will need to create the entity.
See #39
