### ISSUE TITLE
Sleep time

### ISSUE THREAD

**Issue by LukaszP2** [j-a-n/lovelace-wallpanel#5]
Can you do a sleep time that can have oder settings? Fast time to black screen mostly.

**Comment by j-a-n** [comment]
Sorry, can't understand what is meant.
Could you please try to explain better?

**Comment by LukaszP2** [comment]
Option for set the time when settings will be different from standard. Change idle time, black screen after time maybe something else... 
For example: 
Standard: idle time 30, black screen after time 300
Sleep time: set from 22:00 to 8:00,  idle time 15 black screen after time 30

**Comment by kwithus** [comment]
would appreciate such option as well. There is no need for animation or images during night hours, by that the CPU usage would be lower over night and the battery of my (old) ipad used as wall panel could recover over night ;-)

**Comment by kwithus** [comment]
May be it will be easier (and sufficient) to be able to disable the screensaver with an input_boolean, similar as it is already possible to turn it on/off. With that I could disable it over nighttime, saving energy. (my old iPad struggles to load the battery as quick as it is used up by high CPU usage)

**Comment by j-a-n** [comment]
Configuration profiles were introduced with version 2.4.
You can define a `night` profile and activate it by using an text_input helper and an automation.

**Comment by kwithus** [comment]
Thanks for the hint, however, I do need some help with that as I don’t understand the example 

`wallpanel:
  enabled: true
  info_animation_duration_x: 30
  info_animation_duration_y: 20
  style:
    wallpanel-screensaver-overlay:
      background: '#00000000'
  profiles:
    night:
      info_animation_duration_x: 0
      info_animation_duration_y: 0
      style:
        wallpanel-screensaver-overlay:
          background: '#000000bb'
    black:
      black_screen_after_time: 1
  profile: night
  profile_entity: input_text.wallpanel_profile `

At the start of the example there is a definition of info_animation and style, the comes profiles: with night and black (I assume that are 2 different profiles) 
At the end it says profile: night and the profile_entity

First: why is there the definition at the beginning? Is that the ‚standard profile‘ how would I select this, as it has no name?
Second: Why is there a line profile: night? Is that alternatively to selecting the profile by input_text? Does it make sense to select the profile within the yaml?
Third: wouldn’t it be better to have an input_select for the profile to ensure the naming is correct?

well, I will try some different settings today, however, maybe you can give some explanation as well. 
btw: thanks for your efforts, I really love the lovelace_wallpaper.

**Comment by kwithus** [comment]
Ok, I played a little bit around and found out:

the definition for the wallpanel before doing the profile section is something like the ‚standard‘ profile.

(Additional) profiles are added at the end of the Wallpanel definition, after ‚profiles:‘ each different (additional) profile gets an individual name. The „standard“ profiles just has no name or whatever name that is not defined in the profile section.
Working with an input_select list for profile_entity is just fine.

so I added the Profile section from the example, added an input_select.wallpanel_profile with the options: Standard, night, black to HA and now I can change the profile by changing the input_select, which changes the display immediately.
Perfect!
Only remaining question: what is the line profile:night for in the example. I can’t see differences whether I have the line or eliminate it.

**Comment by j-a-n** [comment]
Thank you for the good explaining how the feature works. It would be perfect if you could revise this part of the documentation and create a pull request. The `profile: night` sets the default profile to `night`. But this configuration is just an example to show what is possible and doesn't make too much sense in most cases. You can just omit the attribute.

**Comment by kwithus** [comment]
Ok, first pull request I ever made ;-)
Hope I’ve done it correctly
