### ISSUE TITLE
Ability to disable Screensaver/Idle/Blank options? 

### ISSUE THREAD

**Issue by tokenwizard** [j-a-n/lovelace-wallpanel#50]
If I wanted to disable the screensaver and all other blanking options, how can this be done. Does a value of zero effectively disable these options? 

I have a LCD monitor that I keep Security Cameras and Weather Info displayed on and I need it always visible at a glance. 

Thanks!

**Comment by tokenwizard** [comment]
Disregard. Completely looked over this info in the documentation.

**Comment by tokenwizard** [comment]
Disregard. Completely looked over this info in the documentation.

**Comment by adriel** [comment]
For anyone coming here later, set `idle_time: 0` will disable the screensaver.
