### ISSUE TITLE
supported file formats

### ISSUE THREAD

**Issue by ikolsteren** [j-a-n/lovelace-wallpanel#53]
What file types are supported?
I am playing from a Synology and working great.   Using this to filter out some but still get the odd blank image
I have NEF, ARW and ORF raw files all in the folders.  Not sure of its those causing the issue.   I have not turned on debug yet (not 100% sure how to use) but suspect that its one of these file types in there causing
image_excludes:
  - '\.tif$'
  - '/@eaDir'

**Comment by j-a-n** [comment]
All image types that are supported by the browser.
You can just add `?wp_debug=true` to the url to activate the debug mode (e.g. `http://hass:8123/lovelace/default_view?wp_debug=true`).
With version 4.4 the image path of the current image will always be displayed.

**Comment by ikolsteren** [comment]
Added the debug and sometimes can't see as its black text on black background
I don't have a theme or any settings that should be causing - actually playing on a Google Home display so not dark mode.  Does the same on my PC as well.

**Comment by j-a-n** [comment]
You can add the following to your wallpanel config to change the font color:
```yaml
wallpanel:
  style:
    wallpanel-debug-box:
      color: '#ffffff'
```

**Comment by ikolsteren** [comment]
Perfect - they are JPEG but not sure why they show as black.   Will need to investigate further.
This is actually playing back on my Google Hub which is already a big step to have all my photos played off my NAS to the hub.   it just happens once and a while
