### ISSUE TITLE
Hide safari URL bar on IOS 12

### ISSUE THREAD

**Issue by Vinisz** [j-a-n/lovelace-wallpanel#54]
Hi,

thanks for this nice  job, have it running and looks great.
One question, I want to run this full-screen on a somewhat older Ipad whichis my wall panel in the kitchen.
It runs IOS 12 and cannot go higer.

What are my options ? I tried:

* Adding the webpage to the "home screen" , however, when I open it from there then it just goes to default interface and wallpanel never starts
* Using the home-assistant IOS app, the app works but it seems that wallpanel can only work via the browser, not via the app, is that correct ?
* Using a special "kiosk browser" but I cannot seem to find one in the app store that still works with IOS12

Any suggestions ?

**Comment by j-a-n** [comment]
Wallpanel works in the Home Assistant companion app on Android. I can't say anything about ios as I don't have a device to test.

Wallpanel needs to be enabled via configuration. How did you activate it on the ios 12 device?

I suspect the built in browser components of ios 12 are missing some needed javascript functionality.

Is there a modern browser in the app store for ios 12? If you configure the wallpanel to display in fullscreen mode, that might be a solution.

**Comment by Vinisz** [comment]
Well, I think it all works fine in the safari browser the normal way, I have that running now but then still the URL bar is on top so it looks like it totally ignores the "fullscreen" mode (so, is starts the screensaver just fine, but not "full screen")
I'm using this configuration at the moment:

`wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  keep_screen_on_time: 3600
  black_screen_after_time: 10800
  display_time: 3500
  cards:
    - type: custom:bignumber-card
      entity: sensor.worldclock_sensor
      scale: 80px
    - show_current: true
      show_forecast: true
      type: weather-forecast
      entity: weather.buienradar
      name: ' '
    - type: entity
      entity: sensor.keuken_multisensor_air_temperature`

**Comment by j-a-n** [comment]
Are you able to activate fullscreen mode in safari manually?
Activating fullscreen mode needs a user interaction in most cases. Please try to tap on the screen after the dashboard is loaded.

**Comment by Vinisz** [comment]
No, does not work, what you can do in IOS is add it to the home screen (as an app) and if you launch it from there it goes full screen but, when I do that, it does not load, no idea why not...
Besides this all, I found out that a lot of energy is drawn with safari running the wallpanel, so much that the charger cannot keep-up and battery drains....
I think I just need to replace this device (it's over 5 years old already) with a cheap android tablet, seems there are more possibilities that way also.
What can you recommend as minimum for android ? (which OS, cpu, mem, screenr resolution, etc)

**Comment by j-a-n** [comment]
I would make sure that the screen is of good quality and high resolution. Otherwise, any reasonably up-to-date tablet should suffice.

**Comment by Vinisz** [comment]
Thanks , have it up and running on new cheap Lenovo M10 tablet , works great.
2 questions left (and if you want to have them in new issue then just let me know)

1) Can it also work in the companion app or only in the browser ?
2) I cannot get "transparent" mode to work, I have this config now:

`wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  cards:
    - type: custom:bignumber-card
      entity: sensor.worldclock_sensor
      scale: 120px
    - show_current: true
      show_forecast: true
      type: weather-forecast
      entity: weather.buienradar
      name: ' '
    - type: entity
      entity: sensor.keuken_multisensor_air_temperature
style:
  wallpanel-screensaver-info-box:
    '--wp-card-width': 450px
  wallpanel-screensaver-info-box-content:
    '--ha-card-background': none
    '--ha-card-box-shadow': none
    text-shadow: -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px 0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
    '--primary-text-color': '#ffffff'
    '--secondary-text-color': '#dddddd'
views:
  - theme: ios-dark-mode
    title: Home
    visible:
      - user: 67e537b3b9474e5b85d49600af8b7686
      - user: de7cefdfef2c4f849c5a2d59813b7516
    badges: []
    cards:
      - type: entities
        entities:
          - entity: switch.double_switch_2_18
          - entity: switch.double_switch_2_2_17
        state_color: true
      - square: true
        columns: 4
        type: grid
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: automation.gordijnen_achter_openen
            icon: mdi:curtains
            show_state: false
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: automation.gordijnen_achter_sluiten
            icon: mdi:curtains-closed
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: automation.blinds_voorkant_openen
            icon: mdi:blinds-horizontal-closed
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: automation.blinds_voorkant_sluiten
            icon: mdi:roller-shade-closed
      - type: gauge
        entity: sensor.co2_monitor_air_quality_detector_carbon_dioxide_co2_level
        name: Keuken Co2
        unit: ppm
        min: 250
        max: 3000
        needle: true
        severity:
          green: 750
          yellow: 1500
          red: 1500
      - type: energy-distribution
`

**Comment by j-a-n** [comment]
Yes, wallpanel works in the Android Companion App.
Please reformat your YAML configuration by [quoting-code](https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by knorrre** [comment]
> Yes, wallpanel works in the Android Companion App.
Hello,
in the Companion App on a NS Panel Pro and a Pixel 6 Pro, Wallpanel does not work for me. In the browser it works without any problems. 
What could be the reason that it does not want to run in the apps?
Thanks!

**Comment by j-a-n** [comment]
> What could be the reason that it does not want to run in the apps?
How do you activate wallpanel for your devices?
Did you globally set "enabled: true" in the config?

**Comment by knorrre** [comment]
> Did you globally set "enabled: true" in the config?
Yes, I did. Is there anything else I have to do to enable Wallpanel in the Companion App?

**Comment by j-a-n** [comment]
No, should be sufficient.
Can you try another device?
