### ISSUE TITLE
Use variable for image_url value to support dynamically changing local media path

### ISSUE THREAD

**Issue by zrpierce** [j-a-n/lovelace-wallpanel#55]
j-a-n

Wallpanel has changed the way I use the panels around my home.  I'm so grateful for the work that you put into this.

I use photographs from my local area as the screensaver images and would like to use bright photos in the daytime and darker photos in the evening.  Is there a way to dynamically change the image_url to point to different local media folders?

Thanks

**Comment by j-a-n** [comment]
Glad you like it!
You can work with different profiles for day / evening / night. These profiles can be switched via an automation.
Please have a look at the README and #43.

**Comment by zrpierce** [comment]
That's perfect and I can't believe I didn't catch that.  Thanks again!
