### ISSUE TITLE
Cannot enable integration

### ISSUE THREAD

**Issue by Shivy011** [j-a-n/lovelace-wallpanel#58]
Hi I have installed wallpanel from HACS, shows in frontend fine.

When I add
wallpanel:
  enabled: true
  enabled_on_tabs:
    - default_view
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
to configuration.yaml, the verifier says this is not installed. Also adding it to the dashboard configuration doesn't work either.

Any ideas?

**Comment by josephyancey-apptegy** [comment]
This yaml doesn't go in the configuration.yaml but instead in the raw configuration editor when editing a dashboard.
