### ISSUE TITLE
Extract image URL from JSON

### ISSUE THREAD

**Issue by leoshusar** [j-a-n/lovelace-wallpanel#62]
Hi!
I don't know if you know, but `source.unsplash.com` is being [deprecated](https://changelog.unsplash.com/deprecations/2021/11/25/source-deprecation.html) - it will continue to work, but they won't be adding new images.
The correct way now for getting random images is via their API, they have 50 requests per hour for demo apps, which is perfect for interval one image per 5 minutes which I'm looking for.

Do you have any plans for supporting this? I can make my own web server which would parse the JSON, but if this addon supported it out of the box, it would be great!

**Comment by Wetzel402** [comment]
I have a pull request waiting to add this function.  I actually wrote the code to make an API request for a group of images then cycle through them so I only have 1 call an hour currently.

**Comment by j-a-n** [comment]
The new Unsplash API is now supported in v4.7
