### ISSUE TITLE
Different results on different devices | Transparent black screen

### ISSUE THREAD

**Issue by KyleFreedomSeeds** [j-a-n/lovelace-wallpanel#63]
1. On desktop, the animated weather card acts as expected. It moves in accordance with the configuration. However, when opened on an iPad, it remains static. Interestingly, the "Cloudy" weather status (note the capital C) changes to "cloudy" on the iPad.

Desktop:
![desktop](https://user-images.githubusercontent.com/35439953/206890507-385598b9-d755-46e1-8a40-0ec028e55503.png)

iPad:
![PXL_20221211_065708908 MP](https://user-images.githubusercontent.com/35439953/206890565-31784b46-0018-4a86-b70f-560e23a5641c.jpg)

2. When the screen goes black at the designated interval, elements from the dashboard are still visible in the background. Is this intended?

![dc89330997a9aa8cc57fe4b840e9b182](https://user-images.githubusercontent.com/35439953/206890599-bce1eaf8-743f-4d76-a02f-5cdf19625eb9.png)

**Comment by j-a-n** [comment]
1.) It could be that the browser component on the iPad is too old and does not support CSS animations.
JavaScript based `info_move_pattern` should wor on the iPad.
2.) No, this is not intended. Will be fixed in the next wallpanel version.

**Comment by KyleFreedomSeeds** [comment]
So the update fixed the black screen, thank you.
However, the animation is still not happening on the iPad. I should note that I am using it within the HA iOS app and not a browser such as safari. When using safari, the animations still do not occur. I checked my HA logs and the below error occurs over 4000 times per day:

`http://192.168.1.23:8123/hacsfiles/lovelace-wallpanel/wallpanel.js?hacstag=309506416461:851:24 TypeError: this.infoBox.animate is not a function. (In 'this.infoBox.animate( keyframes, { duration: Math.round(config.info_move_fade_duration * 1000), iterations: 1 } )', 'this.infoBox.animate' is undefined)`

**Comment by j-a-n** [comment]
Your Safari / iOS version seems to be to old to support `animate()`. See: [https://developer.mozilla.org/en-US/docs/Web/API/Element/animate](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate) 

So, you won't be able to use `info_move_pattern` either.
