### ISSUE TITLE
Feature Request - Clock Screen Saver

### ISSUE THREAD

**Issue by Lockie85** [j-a-n/lovelace-wallpanel#64]
Hey,

The andriod app has a Display Setting called "Clock Screen Saver". However, it does not appear these feature works with lovelace-wallpanel.

Could this feature be provided/accessible via lovelace-wallpanel?

Many Thanks

**Comment by j-a-n** [comment]
Hello!
Which app?
What do you want to achieve?

**Comment by Lockie85** [comment]
The wallpanel app
https://wallpanel.app/
I've installed it on my tablet
I assumed it was the basis of this HA add-on?

**Comment by j-a-n** [comment]
No this addon has nothing to do with the app. You can combine the two, but you don't have to.
If you want a clock to be displayed in the screensaver of this addon, just add a corresponding card to the config. You can also configure an animated movement of the card.
