### ISSUE TITLE
Error: Unexpected token '<'

### ISSUE THREAD

**Issue by nghiaphan31** [j-a-n/lovelace-wallpanel#66]
Hi

I just install it via HACS and have this error in my logs upon using it: 

http://homeassistant.local:8123/local/wallpanel.js:1:1 Uncaught SyntaxError: Unexpected token '<'

Any idea?

Thx!

**Comment by j-a-n** [comment]
Hello!
Perhaps the addon download failed?
Please have a look at the local file `/config/www/community/lovelace-wallpanel/lovelace-wallpanel.js`

**Comment by nghiaphan31** [comment]
Hi

I guess you refer to /config/www/community/lovelace-wallpanel/wallpanel.js. It
looks fine to me.

I don't have /config/www/community/lovelace-wallpanel/lovelace-wallpanel.js

I tried to remove and re-install already but still no success.


My config is as follows:

wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  image_url:
https://source.unsplash.com/random/${2048}x${1536}?dogs,cats,nature
#  image_url: /local/media
title: 11_home_view
icon: mdi:home
cards:
  - type: vertical-stack
    cards:
####################################################################################################################################################################################################################################################################################################################################################
####    SURVEILLANCE
####################################################################################################################################################################################################################################################################################################################################################
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            entity: alarm_control_panel.toulouse_alarm
            template: button_alarme
            name: Alarme
          - type: custom:button-card
            template: button_porte_maison
            name: Porte d'entrée
            entity: sensor.ma_porte_entree
          - type: custom:button-card
            template: button_portail
            name: Portail d'entrée
            entity: binary_sensor.capteur_de_portail_entree

**Comment by j-a-n** [comment]
> I guess you refer to /config/www/community/lovelace-wallpanel/wallpanel.js.

Yes, that's right.

> `https://source.unsplash.com/random/${2048}x${1536}?dogs,cats,nature`

This should be `https://source.unsplash.com/random/2048x1536?dogs,cats,nature`
or `https://source.unsplash.com/random/${width}x${height}?dogs,cats,nature`

Perhaps an issue with the browser cache?
