### ISSUE TITLE
Echo Show 15 Full screen option

### ISSUE THREAD

**Issue by robledjl** [j-a-n/lovelace-wallpanel#67]
First of all, great addon...it really adds an awesome look to the echo show that i am using, i am not sure if this is possible or maybe I'm doing something wrong but the dashboard does not fill the screen, i am using fully kiosk and although it does hide the top and left navigation bars, i still have a blank gap on the left, right and bottom of the screen. I'm guessing that will stay like that to keep the dashboard from getting distorted or stretched out to fill the long screen? just wanted to see if i could get some input, I've tried it on my computer and it does look great with the whole screen filled but on the echo show 15 it doesn't fill the screen completely. Thanks.

**Comment by j-a-n** [comment]
Thanks!
I have no device to test with.
Did you try without fully kiosk in a browser or with the companion app (if available)?
Could you please attach a screenshot?

**Comment by robledjl** [comment]
Ive been trying to send you the pictures but it keeps saying message too
large, i tried your recommendation of opening it on a regular browser and
it does fill up the whole screen but using the wp_enabled=true string does
not work, i am using duckdns on the browser so maybe that's the  problem?

**Comment by robledjl** [comment]
Im not sure if you got any of my messages or pictures, gmail was acting up

**Comment by j-a-n** [comment]
You can add your picture here:
https://github.com/j-a-n/lovelace-wallpanel/issues/67

There are better options to enable wallpanel on selected devices: [Profiles](https://github.com/j-a-n/lovelace-wallpanel#profiles)

**Comment by robledjl** [comment]
You can see on the pictures below how the dashboard has gaps on the left and right, it doesn't fill in the whole scree, i tried it on the silk browser that comes with the echo show 15 and it does fill the whole screen but then it's on the whole time, i like your addon that it actually shows random pictures. 


![20221220_174004 (1)](https://user-images.githubusercontent.com/116846736/209355503-6c31c1c6-37a6-4086-85a3-485a2db7383d.jpg)
![20221220_181604](https://user-images.githubusercontent.com/116846736/209355545-f5bdad84-4510-4914-b010-280787ab4761.jpg)

**Comment by j-a-n** [comment]
>  but then it's on the whole time

What do you mean by that?

**Comment by robledjl** [comment]
> > but then it's on the whole time
> 
> What do you mean by that?

Oh, sorry...i meant that when i open it on the silk browser from amazon, it works in full screen and all but the screensaver never kicks in, the dashboard is displayed at all times.

update: I dont know if there was an update or something but i tried chrome and firefox browsers and both are just like the picture above. sorry for all the confusion. As of right now i get it on fully kiosk and browsers at full screen but with those gaps on both sides

**Comment by j-a-n** [comment]
Since I don't have an Echo Show 15 to test, I can't do anything at this time. If someone can give more relevant information, we can open the issue again.
