### ISSUE TITLE
Wallpanel can not be actived for a specific user only

### ISSUE THREAD

**Issue by stefanschaedeli** [j-a-n/lovelace-wallpanel#68]
Maybe more a feature request than an issue... 

When I start my iphone app, the wallpaper did now somehow activate in the background and starts loading everytime I open the app. on my wallmounted Ipad I like the wallpanel to run, but only there. The easiest solution for me would be to be able to select the specific user rather than run on all devices.

as the ipad on the wall runs as well the app, I cant use the "url mod"

**Comment by j-a-n** [comment]
This is already possible.
With profiles you can activate wallpanel for specific users or specific devices (using browser mod).
See [Profiles](https://github.com/j-a-n/lovelace-wallpanel#profiles)
