### ISSUE TITLE
Dim Enables

### ISSUE THREAD

**Issue by curtisdr** [j-a-n/lovelace-wallpanel#70]
On my Fire Tablet 10 HD (9th gen, OS 7.3.2.6) the screen dims after what I assume is the screensaver timeout,   It does not do that on my three 11th gen (OS 7.3.2.6).  Each tab has it's own Lovelace's, but all start with the following except for the enable_on_tabs names (sorry the formatting doesn't display properly here):

`wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: true
  idle_time: 0
  fullscreen: true
  keep_screen_on_time: 0
  black_screen_after_time: 0
  enabled_on_tabs:
    - foyer_home
    - foyer_cameras
  `

**Comment by j-a-n** [comment]
The `keep_screen_on_time` specifies the time in seconds for how long to prevent the screen to dimm or lock.
0 means disabled.
Please try to set `keep_screen_on_time` value to something bigger like 86400 (1 day).

**Comment by curtisdr** [comment]
Easy enough to do, but odd dimming never occurs on my 11th gen tablets.
