### ISSUE TITLE
Exit Fullscreen

### ISSUE THREAD

**Issue by BristolBEAT** [j-a-n/lovelace-wallpanel#72]
How do you exist fullscreen and access the raw config yaml? Need to also edit the Dashboard

**Comment by j-a-n** [comment]
This depends on the browser.
You can try <F11> or <ESC>.
You can add `?wp_enabled=false` or `?wp_fullscreen=false` to the URL to disable wallpanel / fullscreen.
For example: `http://hass:8123/lovelace/default_view?wp_fullscreen=false`.
