### ISSUE TITLE
Not casting to Chromecast

### ISSUE THREAD

**Issue by jfdid** [j-a-n/lovelace-wallpanel#73]
Hi, great project.
The wallpanel screensaver works on my PC browser, but when I try to play it on my Chromecast(tv/hdmi), it just shows a black screen.  The weather widget doesn't float around and I don't have any photos on the screensaver.  Other HA dashboards cast fine.
I'm accessing via either local http://192.168.x.x or Nabu Casa address.
Photos are referenced by   image_url: media-source://media_source
Any thoughts?  Thanks!

**Comment by nebriv** [comment]
I'm also having this issue - when casting I just get a white screen.

**Comment by mtandrup** [comment]
I believe I have the same issue.

I cast my dashboard to a Google Nest Hub 2nd gen and the wallpanel never starts.

**Comment by j-a-n** [comment]
I currently have no Chromecast to test with, sorry.
