### ISSUE TITLE
Exif Data Encoding

### ISSUE THREAD

**Issue by TechNiggo** [j-a-n/lovelace-wallpanel#75]
Special characters in the exif data like äöü or á are not shown correctly. E.g. Ã¶ is shown for an ö. This is likely caused by the wrong encoding. The exif-data is in utf8 but interpreted as ascii by the tool.

**Comment by j-a-n** [comment]
Could you please provide an example file?

**Comment by TechNiggo** [comment]
Brúafoss is written in the Exif Data but the ú is not displayed correctly as you can see in the screenshot
![image](https://user-images.githubusercontent.com/33681709/216702465-c707968b-7ab5-4df3-8835-e48291540643.png)
Here is the image with the exif information. 
![DSC02548](https://user-images.githubusercontent.com/33681709/216702559-ed273e34-1763-4f7e-a3d1-7468f88b3228.jpg)
Thank you

**Comment by j-a-n** [comment]
Should be fixed in v4.7

**Comment by TechNiggo** [comment]
It's working now. Thank you very much
