### ISSUE TITLE
Photoprism integration

### ISSUE THREAD

**Issue by smathev** [j-a-n/lovelace-wallpanel#77]
Hi.

Thanks for a really cool plugin/interface improvement. I'm using [PhotoPrism ](https://photoprism.app/)to locally manage my photos and was wondering if there was a way to implement that as the image source.

Ideally what I would like was that I in PhotoPrism could add a tag to images I wanted used in WallPanel, and WallPanel would then only use images from that part of PhotoPrism.

The path for a set of images in Photoprism with a specific tag/label is: 
For instance: `{Domain}/library/all?q=label%3Aaircraft`, `{Domain}/library/all?q=label%3Aanimal` - so, a more general would be: `{Domain}/library/all?q=label%3A[Tag]`

So, my suggestion would be if wallpanel could use that URL to search for images, for instance: `{Domain}/library/all?q=label%3AHomeAssistant`

The issue being right now, that apparently that URL doesn't return a list of images. 

All in all, is it possible to implement PhotoPrism and use it's photo-album qualities to easier curate a list of relevant photographic memories to use in WallPanel?

Thanks in advance - and thank you for the awesome piece of software!

**Comment by j-a-n** [comment]
What does the response to a request to `{domain}/library/all?q=label%3A[tag]` look like?
Does it return json data?
