### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier 'to'

### ISSUE THREAD

**Issue by Jonny-T-cyber** [j-a-n/lovelace-wallpanel#78]
Hi all!
In Log Viewer I have this errpr:

2023-01-27 00:43:43.911 ERROR (MainThread) [frontend.js.latest.202301100] https://MY_DOMAIN.duckdns.org:8123/local/wallpanel.js:1:6 Uncaught SyntaxError: Unexpected identifier 'to'

Does anyone have the same error or know what it is?
Thanks

**Comment by j-a-n** [comment]
Looks like the the wallpanel.js file is corrupted.
Please try to reinstall the addon and clear the browser cache.
You can also have a look at the files in /config/www/community/lovelace-wallpanel
Which files are there?

**Comment by Jonny-T-cyber** [comment]
> Looks like the the wallpanel.js file is corrupted.
> Please try to reinstall the addon and clear the browser cache.
> You can also have a look at the files in /config/www/community/lovelace-wallpanel
> Which files are there?
>

**Comment by Jonny-T-cyber** [comment]
![Uploading Screenshot_20230219_231529.jpg …]()
