### ISSUE TITLE
Add option for local date formatting.

### ISSUE THREAD

**Issue by TechNiggo** [j-a-n/lovelace-wallpanel#81]
The toLocaleDateString() function has an option to display the date in a local format. 

It would be awesome to have a parameter in the wallpanel section. Like image_info_date_format: "de-DE". Currently undefined is used there. 
https://github.com/j-a-n/lovelace-wallpanel/blob/e4063729a0db94606596b1fb1c00376223cd6fad/wallpanel.js#L1287

**Comment by j-a-n** [comment]
`date.toLocaleDateString(undefined, options)` should use the browsers default locale.
Which browser are you using and what are your language settings?
But anyway, I can add a corresponding configuration in one of the next versions.

**Comment by j-a-n** [comment]
Version 4.7.2 is now using HA language settings to format the date.
Please try it out.

**Comment by TechNiggo** [comment]
It's is working. Thank you very much :)
