### ISSUE TITLE
Toolbar disappears

### ISSUE THREAD

**Issue by bsamob** [j-a-n/lovelace-wallpanel#82]
On my tablet in kiosk mode I use wallpanel. I use yaml for all my HA config. Editing the dashboard yaml for my tablet I entered 'hide_toolbar: false' For a while it worked fine, but after some time and refreshs because I still change a lot my cards on the dashboard, the false value of this setting is not working anymore, the toolbar is gone even if it is set to false.
I noticed that setting it to true, refresh the dashboard on the tablet, setting it back to false and refresh again the toolbar is shown again for some time. But then again it begins again, after some time it disappears.
I did not notice anything else failing.

**Comment by j-a-n** [comment]
Could you please share the wallpanel part of your dashboard config?

**Comment by bsamob** [comment]
Sure, these are the first few lines:
'title: Kiosk
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: true
  fullscreen: true
  image_url: https://source.unsplash.com/random/${1920}x${1080}?dogs,nature,mountains
  info_animation_duration_x: 180
  info_animation_duration_y: 180
  info_animation_timing_function_x: linear
  info_animation_timing_function_y: linear
  style:
    wallpanel-screensaver-info-box:
      "--wp-card-width": 350px
    wallpanel-screensaver-info-box-content:
      "--ha-card-background": "rgba(0, 0, 0, 0.4)"
      "--ha-card-box-shadow": none
      text-shadow: -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px 0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
      "--primary-text-color": "#ffffff"
      "--secondary-text-color": "#eeeeee"
  cards:'

Please let me know, if you need anything more.

**Comment by bsamob** [comment]
[kiosk.yaml.txt](https://github.com/j-a-n/lovelace-wallpanel/files/10833767/kiosk.yaml.txt)

**Comment by bsamob** [comment]
Seems to be solved by the recent updates.
Thanks
