### ISSUE TITLE
Local source, scan recursively 

### ISSUE THREAD

**Issue by neuroverflow** [j-a-n/lovelace-wallpanel#85]
Hi! Not a bug but more a feature request ...
Using local resources (image_url: /local/PhotosKiosk   image_order: random) don't pick photos in subfolders. 
Would be nice to have an option to scan for photos recursively.
Thank you for considering it!

**Comment by j-a-n** [comment]
This should actually work. Folders are always searched recursively for images.
Do error messages appear in the browser console?
You can activate the debug mode to get more messages about the image search process in the browser console.

**Comment by neuroverflow** [comment]
hum ... So I don't know if the last updates did anything good or maybe rebooting HA ... 
But now it works perfectly. I only have photos in subfolders, nothing on the root and I can see now random photos from those folders.
Amazing, Great job on that extension!
