### ISSUE TITLE
Fully Kiosk Browser - Background image

### ISSUE THREAD

**Issue by it00x32** [j-a-n/lovelace-wallpanel#86]
Hi, first of all: great work - I love the wall panel running as my screensaver. 
But I have issues with my FireTablet 10 running fully kiosk browser. 
The Image is not loading, even in the default setting without any image tag. Same config is working on Chrome and Safari.

![unnamed](https://user-images.githubusercontent.com/66878794/226319985-90cda6aa-fa3d-4b51-85ff-774663b1aea2.png)

**Comment by j-a-n** [comment]
Seems like Fully Kiosk Browser can't access the internet.
Perhaps some Fully Kiosk Browser settings missing?
Please have a look at:
https://smarthomepursuits.com/fire-tablet-fully-kiosk-screensaver-home-assistant/

**Comment by LukaszP2** [comment]
I use it on amazon echo15 with FKB and localy, photogoogle and internet image s works for me.

**Comment by j-a-n** [comment]
Seems to be an Fully Kiosk Browser issue.
