### ISSUE TITLE
Energy distribution card not updating

### ISSUE THREAD

**Issue by Vinisz** [j-a-n/lovelace-wallpanel#87]
Hi,

I have wallpanel running just fine (on android tablet) however, the "energy distribution" card is not updating/resetting (I think overnight)
It's of type: energy-distribution. 
Any idea what causes this ? all other cards update just fine

**Comment by j-a-n** [comment]
Please try if version 4.9.1 fixes the issue.

**Comment by Blackhawk386** [comment]
Hi,

I'm on version 4.10.0 and have the same problem. It would be great if you can fix or figure out the problem.

**Comment by j-a-n** [comment]
This should now work with version 4.10.1.

**Comment by Blackhawk386** [comment]
It works! Thanks a lot for your great work!

**Comment by Vinisz** [comment]
@j-a-n , this is interesting... to test if the issue was with "wallpanel" I disabled it and just let a normal dashboard run on my always-on android tablet in the kitchen (via the companion app) 
And, to my surprise, the problem also appears in a "normal dashboard" (as also mentioned here: https://community.home-assistant.io/t/energy-distribution-today-not-automatically-updating/453139/5)
So, I'm glad you fixed it but maybe you can help out others who just use normal dashboard as well with your solution ? that would be awesome
