### ISSUE TITLE
Firefox high CPU/GPU usage: caused by ScreenWakeLockVideo?

### ISSUE THREAD

**Issue by backcountrymountains** [j-a-n/lovelace-wallpanel#90]
I serve HA using https using let's encrypt and duckdns but Wallpanel is playing the ScreenWakeLockVideo all the time. This causes relatively high (50%) CPU usage with a fair amount of GPU usage on my computer when I have the tab open in Firefox (Firefox 111 Windows 10). I don't think this happens using Chrome.
Is there a way to prevent this?
Why would Wallpanel be using the ScreenWakeLockVideo instead of the native wakelock?

![image](https://user-images.githubusercontent.com/29560911/229169857-bd632abc-192c-46ed-b293-bc80f9a774e9.png)

![image](https://user-images.githubusercontent.com/29560911/229171255-865ec8f3-5893-4034-bfef-af9f33afc958.png)

Disabling Wallpanel stops CPU/GPU use.

I really like using Wallpanel on my tablets so I hope to find a solution!

Thanks.
```
Application
Name and version:Firefox 111
Update channel:release
Build ID:[20230321111920](https://hg.mozilla.org/releases/mozilla-release/rev/6e9b4327e238def619d5640de74b611fe51834ba)
Build type:Opt
Extensions:

    Add-ons Search Detection
    Amazon.com
    Bing
    Bionic Reader
    Bypass Paywalls Clean
    DuckDuckGo
    FireMonkey
    Firefox Screenshots
    Form Autofill
    Google
    NoScript
    Picture-In-Picture
    Privacy Badger
    System theme — auto
    The Stream Detector
    Web Compatibility Interventions
    Wikipedia (en)
    eBay
    uBlock Origin

Platform
OS:Windows 10
ABI:x86_64-msvc
CPU model:Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
CPU cores:⁨⁨6⁩ physical cores⁩, ⁨⁨6⁩ logical cores⁩
I also have a 1660ti
```

**Comment by j-a-n** [comment]
In v4.9.0 I replaced the WakeLock video with an 8x8 1fps x264 video.
Please test if this reduces CPU/GPU usage with Firefox.
However, the previous video was already very small. It could also be a driver problem or a problem with Firefox.

**Comment by backcountrymountains** [comment]
It's a little better (overall CPU 20%, GPU 1%) but it seems like just a failing of Firefox (or just particular to me).
What do you think of adding a configuration parameter to enable/disable the video wakelock?
For now I've just commented out the non-native wakelock section, as it isn't necessary for my enjoyment of the Wallpanel.

Thanks for making Wallpanel!

**Comment by j-a-n** [comment]
You can disable the wake lock by setting `keep_screen_on_time` to `0`.
You can use [profiles](https://github.com/j-a-n/lovelace-wallpanel#profiles) to set a value for specific devices only.
