### ISSUE TITLE
cant recover toolbar

### ISSUE THREAD

**Issue by gizbod** [j-a-n/lovelace-wallpanel#95]
after installing on 2 separate dashboards, 1 functions correctly and the tool bar reappears when I add ?wp_enabled=false.
the other dashboard which is ui controlled only recovers the side panel.

basic config was added
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true

I can no longer access my config editor for this dashboard.
any suggestions?
thanks

**Comment by j-a-n** [comment]
You can add `?edit=1` to the URL.
This should take you to dashboard in edit mode.

**Comment by gizbod** [comment]
That solves part of the problem. 
I can edit my cards using this. 
but still can’t access raw config editor to edited the wall panel configuration.

**Comment by gizbod** [comment]
I’m such an idiot. 
I turned kiosk mode off but left disable header on. 

Used ?wp_enabled=false%disable_km

now it’s come back. 
sorry, you can now close this issue.
