### ISSUE TITLE
Updating to v4.9.1 side bar is no longer hidden

### ISSUE THREAD

**Issue by swampylee** [j-a-n/lovelace-wallpanel#97]
Home Assistant dashboards displayed through Fully Kiosk were working perfectly prior to the latest update and now none of them automatically hide the bar on the left hand side. As can be seen in the attached.

![IMG_1460](https://user-images.githubusercontent.com/52431327/231267856-3e82cacb-6ced-4b22-8c77-8b6c579194c9.jpg)

Just manually downgraded to 4.9.0 and still the problem exists through both Chrome and on my tablets.

Update: downgraded to v4.8.1 and everything is back to normal.

**Comment by j-a-n** [comment]
Please test if version 4.10.0 fixes the issue.
