### ISSUE TITLE
Option to dim/tint screen

### ISSUE THREAD

**Issue by NickBootOne** [j-a-n/lovelace-wallpanel#99]
First of all, I love the project !
Came here because a forked project has set the status to deprecated 

One option that I mis is the option to dim the screen when wallpaper shows some pictures.
Or some kind of tint option to darken the pictures

forked project had this option:
https://github.com/Shreyas-R/lovelace-wallpanel-screensaver

screensaver_tint

Really liked it because the screen wouldn't be so bright in some conditions 

Would it be possible to add this ?

**Comment by NickBootOne** [comment]
Ah okay, looked over that feature.

Sorry 😅

**Comment by ILiveInAHouse** [comment]
@j-a-n , it looks like this overlay background also covers the cards.  I was hoping to dim the image behind the cards so that the text of the cards would pop out more on a bright display.  Is there a background dim option that doesn't also dim the cards?

**Comment by j-a-n** [comment]
Just added a new div `wallpanel-screensaver-image-overlay` in version 4.19.0.
So you can now use:
```yaml
  style:
    wallpanel-screensaver-image-overlay:
      background: '#000000bb'
```

**Comment by ILiveInAHouse** [comment]
This works great!  Thanks!
